/**
 * Single source of truth for product branding: display name, logo assets,
 * and theme colors. Everything else (tailwind.config.ts, Sidebar's logo,
 * the browser tab title) reads FROM this file -- nothing downstream should
 * hardcode a color, a name string, or a logo path of its own.
 *
 * `theme` is itself a generated file (see theme.generated.ts's header) --
 * it is the OUTPUT of scripts/generate-theme.mjs run against `logo.full`,
 * not something hand-edited here.
 *
 * displayName stays "EAMI" deliberately -- the visual logo below already
 * reads "rheoARC", but the text name change is a separate, deferred
 * rebrand decision (see CONTEXT.md's product-identity note). Change this
 * one value and every consumer (currently: the browser tab title) follows.
 */
import { brand } from './theme.generated'
import logoFullUrl from './source/rheoarc-logo.png'

export const branding = {
  displayName: 'EAMI',
  logo: {
    // Large lockup -- used wherever there's room for the full wordmark
    // (today: the sidebar header).
    full: logoFullUrl,
    // Small/icon-only mark -- used wherever space is too tight for the
    // wordmark (today: nowhere in the app yet, no collapsed sidebar rail
    // exists; reserved for one). PLACEHOLDER: the source logo is a
    // wordmark only (no icon glyph in the original asset), so this is a
    // generated monogram in the extracted brand colors, not a real
    // designed mark -- see LogoMark in Logo.tsx and BUILT.md.
  },
  favicon: '/favicon.svg', // generated by scripts/generate-theme.mjs
  theme: {
    brand,
  },
} as const

export type Branding = typeof branding
