/**
 * AUTO-GENERATED by scripts/generate-theme.mjs -- do not hand-edit.
 * Regenerate with: npm run generate-branding-theme
 *
 * Source logo: Logo/rheo logo name.png
 * Generated:   2026-08-22T10:46:50.570Z
 *
 * Extraction: colorthief.getSwatches() (MMCQ quantization, ignoreWhite:true)
 * against the trimmed logo found 4 real swatch(es). The
 * lowest-lightness swatch is the bold navy "ARC" glyph (anchors brand-500
 * below); the highest-chroma swatch OTHER than that navy anchor is the
 * teal "rheo" glyph (kept as a reference below, not wired into the ramp) --
 * chroma, not lightness, picks it out because PNG anti-aliasing along the
 * glyph edges produces pale near-white swatches that are lighter than the
 * real teal fill but aren't a genuine second logo color.
 * The 50/100/600/700/900 steps are NOT separately sampled colors -- each is
 * computed from the navy anchor by holding its OKLCH hue+chroma constant
 * and moving only lightness (tapering chroma near the extremes to stay in
 * sRGB gamut), per Bjorn Ottosson's OKLab model. brand-500 is the exact
 * extracted hex, unmodified.
 */

export const rawSwatches = {
  navy: "#133f6d",
  teal: "#1b8492",
} as const

export const brand = {
  "50": "#e6f7ff",
  "100": "#d5eaff",
  "500": "#133f6d",
  "600": "#002c58",
  "700": "#001a44",
  "900": "#000019"
} as const
