// Code generated by sqlc from internal/store/query/agents.sql. DO NOT EDIT directly.
package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listAgents = `-- name: ListAgents :many
SELECT id, org_id, name, model, owner, scope, risk_tier, status,
       token_ttl_seconds, created_by, created_at, updated_at, last_seen
FROM gateway_agents
WHERE org_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR risk_tier = $3)
ORDER BY name ASC
`

func (q *Queries) ListAgents(ctx context.Context, orgID uuid.UUID, status, riskTier *string) ([]GatewayAgent, error) {
	rows, err := q.db.Query(ctx, listAgents, toPgtypeUUID(orgID), toPgtypeText(status), toPgtypeText(riskTier))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var agents []GatewayAgent
	for rows.Next() {
		var a GatewayAgent
		if err := rows.Scan(
			&a.ID, &a.OrgID, &a.Name, &a.Model, &a.Owner, &a.Scope,
			&a.RiskTier, &a.Status, &a.TokenTTLSeconds,
			&a.CreatedBy, &a.CreatedAt, &a.UpdatedAt, &a.LastSeen,
		); err != nil {
			return nil, err
		}
		agents = append(agents, a)
	}
	return agents, rows.Err()
}

const getAgent = `-- name: GetAgent :one
SELECT id, org_id, name, model, owner, scope, risk_tier, status,
       token_ttl_seconds, created_by, created_at, updated_at, last_seen
FROM gateway_agents
WHERE id = $1 AND org_id = $2
LIMIT 1
`

func (q *Queries) GetAgent(ctx context.Context, id, orgID uuid.UUID) (*GatewayAgent, error) {
	row := q.db.QueryRow(ctx, getAgent, toPgtypeUUID(id), toPgtypeUUID(orgID))
	var a GatewayAgent
	err := row.Scan(
		&a.ID, &a.OrgID, &a.Name, &a.Model, &a.Owner, &a.Scope,
		&a.RiskTier, &a.Status, &a.TokenTTLSeconds,
		&a.CreatedBy, &a.CreatedAt, &a.UpdatedAt, &a.LastSeen,
	)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

type CreateAgentParams struct {
	OrgID           uuid.UUID
	Name            string
	Model           string
	Owner           string
	Scope           string
	RiskTier        string
	TokenTTLSeconds int32
	CreatedBy       pgtype.UUID
}

const createAgent = `-- name: CreateAgent :one
INSERT INTO gateway_agents (org_id, name, model, owner, scope, risk_tier, token_ttl_seconds, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, model, owner, scope, risk_tier, status,
          token_ttl_seconds, created_by, created_at, updated_at, last_seen
`

func (q *Queries) CreateAgent(ctx context.Context, p CreateAgentParams) (*GatewayAgent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		toPgtypeUUID(p.OrgID), p.Name, p.Model, p.Owner, p.Scope,
		p.RiskTier, p.TokenTTLSeconds, p.CreatedBy,
	)
	var a GatewayAgent
	err := row.Scan(
		&a.ID, &a.OrgID, &a.Name, &a.Model, &a.Owner, &a.Scope,
		&a.RiskTier, &a.Status, &a.TokenTTLSeconds,
		&a.CreatedBy, &a.CreatedAt, &a.UpdatedAt, &a.LastSeen,
	)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

type UpdateAgentParams struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	Scope           pgtype.Text
	RiskTier        pgtype.Text
	Status          pgtype.Text
	TokenTTLSeconds pgtype.Int4
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE gateway_agents SET
    scope            = COALESCE($3, scope),
    risk_tier        = COALESCE($4, risk_tier),
    status           = COALESCE($5, status),
    token_ttl_seconds = COALESCE($6, token_ttl_seconds)
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, model, owner, scope, risk_tier, status,
          token_ttl_seconds, created_by, created_at, updated_at, last_seen
`

func (q *Queries) UpdateAgent(ctx context.Context, p UpdateAgentParams) (*GatewayAgent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		toPgtypeUUID(p.ID), toPgtypeUUID(p.OrgID),
		p.Scope, p.RiskTier, p.Status, p.TokenTTLSeconds,
	)
	var a GatewayAgent
	err := row.Scan(
		&a.ID, &a.OrgID, &a.Name, &a.Model, &a.Owner, &a.Scope,
		&a.RiskTier, &a.Status, &a.TokenTTLSeconds,
		&a.CreatedBy, &a.CreatedAt, &a.UpdatedAt, &a.LastSeen,
	)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM gateway_agents WHERE id = $1 AND org_id = $2
`

func (q *Queries) DeleteAgent(ctx context.Context, id, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgent, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return err
}
