// Code generated by sqlc from internal/store/query/agent_connections.sql. DO NOT EDIT directly.
//
// B-200: the real, scoped relationship graph on the new Agent Detail page
// (DESIGN_SYSTEM.md §7.1). Four queries, one per relationship type, each
// using the real, already-existing linkage this brief's own Part A
// investigation confirmed -- no new columns, no new tables.
package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// AgentToolConnection is one distinct tool this agent has actually
// dispatched through, per audit_log. audit_log.tool_name is free text (no
// tool_id FK) -- LEFT JOINed to gateway_tools by (org_id, name), so a since-
// renamed/deleted connector correctly comes back with ToolID == nil, the
// same dangling-reference shape WorkflowStep already established for
// gateway_tool_id (workflows.go's GetWorkflow).
type AgentToolConnection struct {
	ToolID         *uuid.UUID
	ToolName       string
	CallCount24h   int64
	CallCountTotal int64
	LastDispatchAt time.Time
}

const listAgentToolConnections = `-- name: ListAgentToolConnections :many
SELECT
    gt.id,
    a.tool_name,
    count(*) FILTER (WHERE a.timestamp > now() - interval '24 hours') AS call_count_24h,
    count(*) AS call_count_total,
    max(a.timestamp) AS last_dispatch_at
FROM audit_log a
LEFT JOIN gateway_tools gt ON gt.org_id = a.org_id AND gt.name = a.tool_name
WHERE a.org_id = $1 AND a.agent_id = $2
GROUP BY gt.id, a.tool_name
ORDER BY call_count_total DESC, a.tool_name ASC
`

// ListAgentToolConnections lists every tool this agent has real audit_log
// history dispatching through, most-called first. Empty (not an error) for
// an agent with zero dispatch history -- an honest state, not a bug.
func (q *Queries) ListAgentToolConnections(ctx context.Context, orgID, agentID uuid.UUID) ([]AgentToolConnection, error) {
	rows, err := q.db.Query(ctx, listAgentToolConnections, toPgtypeUUID(orgID), toPgtypeUUID(agentID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []AgentToolConnection
	for rows.Next() {
		var c AgentToolConnection
		var toolID pgtype.UUID
		if err := rows.Scan(&toolID, &c.ToolName, &c.CallCount24h, &c.CallCountTotal, &c.LastDispatchAt); err != nil {
			return nil, err
		}
		c.ToolID = uuidPtrFromPgtype(toolID)
		out = append(out, c)
	}
	return out, rows.Err()
}

// AgentPolicyConnection is one policy that has actually applied to a real
// audit_log decision for this agent -- NOT every policy whose conditions
// could theoretically match this agent (policies match on tool/action
// conditions, not agent identity, so there is no direct "assigned to this
// agent" relationship to query). A dispatch that hit no specific policy
// rule (a bare default-allow) has audit_log.policy_id == NULL and
// contributes nothing here -- an honest empty result for an agent whose
// traffic never matched a rule, not a bug. Confirmed against
// eami-gateway/cmd/gateway/dispatcher.go: PolicyID is set from the
// evaluator's own decision.PolicyID uniformly across the allowed/denied/
// escalated branches, not just one of them.
type AgentPolicyConnection struct {
	PolicyID uuid.UUID
	Name     string
	Action   string
}

const listAgentPolicyConnections = `-- name: ListAgentPolicyConnections :many
SELECT DISTINCT p.id, p.name, p.action
FROM audit_log a
JOIN policies p ON p.id = a.policy_id
WHERE a.org_id = $1 AND a.agent_id = $2
ORDER BY p.name ASC
`

func (q *Queries) ListAgentPolicyConnections(ctx context.Context, orgID, agentID uuid.UUID) ([]AgentPolicyConnection, error) {
	rows, err := q.db.Query(ctx, listAgentPolicyConnections, toPgtypeUUID(orgID), toPgtypeUUID(agentID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []AgentPolicyConnection
	for rows.Next() {
		var c AgentPolicyConnection
		if err := rows.Scan(&c.PolicyID, &c.Name, &c.Action); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// AgentWorkflowConnection is one workflow this agent genuinely has a real
// run of. workflow_runs.agent_id is a direct FK to gateway_agents (schema/
// migrations-v2/000007_workflow_execution.up.sql) -- simpler and more
// direct than chaining through audit_log.workflow_run_id (B-093), which
// this query deliberately does not use.
type AgentWorkflowConnection struct {
	WorkflowID uuid.UUID
	Name       string
}

const listAgentWorkflowConnections = `-- name: ListAgentWorkflowConnections :many
SELECT DISTINCT w.id, w.name
FROM workflow_runs wr
JOIN workflows w ON w.id = wr.workflow_id
WHERE wr.org_id = $1 AND wr.agent_id = $2
ORDER BY w.name ASC
`

func (q *Queries) ListAgentWorkflowConnections(ctx context.Context, orgID, agentID uuid.UUID) ([]AgentWorkflowConnection, error) {
	rows, err := q.db.Query(ctx, listAgentWorkflowConnections, toPgtypeUUID(orgID), toPgtypeUUID(agentID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []AgentWorkflowConnection
	for rows.Next() {
		var c AgentWorkflowConnection
		if err := rows.Scan(&c.WorkflowID, &c.Name); err != nil {
			return nil, err
		}
		out = append(out, c)
	}
	return out, rows.Err()
}

// AgentEndpointConnection is the single real endpoint explicitly linked to
// this agent (B-164's endpoints.gateway_agent_id -- a nullable FK, at most
// one per agent by the schema's own single-column design, not a join
// table). GetAgentEndpointConnection returns pgx.ErrNoRows when none is
// linked -- the caller (agents.go) treats that as endpoint: null, not an
// error.
type AgentEndpointConnection struct {
	EndpointID uuid.UUID
	Hostname   string
}

const getAgentEndpointConnection = `-- name: GetAgentEndpointConnection :one
SELECT id, hostname
FROM endpoints
WHERE org_id = $1 AND gateway_agent_id = $2
LIMIT 1
`

func (q *Queries) GetAgentEndpointConnection(ctx context.Context, orgID, agentID uuid.UUID) (*AgentEndpointConnection, error) {
	row := q.db.QueryRow(ctx, getAgentEndpointConnection, toPgtypeUUID(orgID), toPgtypeUUID(agentID))
	var e AgentEndpointConnection
	if err := row.Scan(&e.EndpointID, &e.Hostname); err != nil {
		return nil, err
	}
	return &e, nil
}
