// Code generated by sqlc from internal/store/query/alerts.sql. DO NOT EDIT directly.
// NOTE: requires migration 003_alerts.sql for status/acknowledged/metric_value columns.
package store

import (
	"context"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ── alert_rules ───────────────────────────────────────────────────────────────

func scanAlertRule(row interface{ Scan(...any) error }) (*AlertRule, error) {
	var r AlertRule
	err := row.Scan(
		&r.ID, &r.OrgID, &r.Name, &r.Description, &r.Condition, &r.ConditionConfig,
		&r.Severity, &r.Channels, &r.Enabled, &r.CreatedBy, &r.CreatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &r, nil
}

const alertRuleCols = `id, org_id, name, description, condition, condition_config,
       severity, channels, enabled, created_by, created_at`

const listAlertRulesQuery = `SELECT ` + alertRuleCols + ` FROM alert_rules WHERE org_id = $1 ORDER BY created_at DESC`

func (q *Queries) ListAlertRules(ctx context.Context, orgID uuid.UUID) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAlertRulesQuery, toPgtypeUUID(orgID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []AlertRule
	for rows.Next() {
		r, err := scanAlertRule(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *r)
	}
	return out, rows.Err()
}

const listAllActiveAlertRulesQuery = `SELECT ` + alertRuleCols + ` FROM alert_rules WHERE enabled = TRUE`

func (q *Queries) ListAllActiveAlertRules(ctx context.Context) ([]AlertRule, error) {
	rows, err := q.db.Query(ctx, listAllActiveAlertRulesQuery)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []AlertRule
	for rows.Next() {
		r, err := scanAlertRule(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *r)
	}
	return out, rows.Err()
}

const getAlertRuleQuery = `SELECT ` + alertRuleCols + ` FROM alert_rules WHERE id = $1 AND org_id = $2`

func (q *Queries) GetAlertRule(ctx context.Context, id, orgID uuid.UUID) (*AlertRule, error) {
	return scanAlertRule(q.db.QueryRow(ctx, getAlertRuleQuery, toPgtypeUUID(id), toPgtypeUUID(orgID)))
}

type CreateAlertRuleParams struct {
	OrgID           uuid.UUID
	Name            string
	Description     pgtype.Text
	Condition       string
	ConditionConfig []byte
	Severity        string
	Channels        []string
	Enabled         bool
	CreatedBy       pgtype.UUID
}

const createAlertRuleQuery = `INSERT INTO alert_rules
    (org_id, name, description, condition, condition_config, severity, channels, enabled, created_by)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
RETURNING ` + alertRuleCols

func (q *Queries) CreateAlertRule(ctx context.Context, p CreateAlertRuleParams) (*AlertRule, error) {
	channels := p.Channels
	if channels == nil {
		channels = []string{}
	}
	return scanAlertRule(q.db.QueryRow(ctx, createAlertRuleQuery,
		toPgtypeUUID(p.OrgID), p.Name, p.Description, p.Condition, p.ConditionConfig,
		p.Severity, channels, p.Enabled, p.CreatedBy,
	))
}

type UpdateAlertRuleParams struct {
	ID              uuid.UUID
	OrgID           uuid.UUID
	Name            pgtype.Text
	Description     pgtype.Text
	Condition       pgtype.Text
	ConditionConfig []byte
	Severity        pgtype.Text
	Channels        []string
	Enabled         *bool
}

const updateAlertRuleQuery = `UPDATE alert_rules SET
    name             = COALESCE($3, name),
    description      = COALESCE($4, description),
    condition        = COALESCE($5, condition),
    condition_config = COALESCE($6, condition_config),
    severity         = COALESCE($7, severity),
    channels         = COALESCE($8, channels),
    enabled          = COALESCE($9, enabled)
WHERE id = $1 AND org_id = $2
RETURNING ` + alertRuleCols

func (q *Queries) UpdateAlertRule(ctx context.Context, p UpdateAlertRuleParams) (*AlertRule, error) {
	var enabledArg interface{}
	if p.Enabled != nil {
		enabledArg = *p.Enabled
	}
	var channelsArg interface{}
	if p.Channels != nil {
		channelsArg = p.Channels
	}
	return scanAlertRule(q.db.QueryRow(ctx, updateAlertRuleQuery,
		toPgtypeUUID(p.ID), toPgtypeUUID(p.OrgID),
		p.Name, p.Description, p.Condition, p.ConditionConfig,
		p.Severity, channelsArg, enabledArg,
	))
}

const deleteAlertRuleQuery = `DELETE FROM alert_rules WHERE id = $1 AND org_id = $2`

func (q *Queries) DeleteAlertRule(ctx context.Context, id, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlertRuleQuery, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return err
}

// ── alerts ────────────────────────────────────────────────────────────────────

func scanAlert(row interface{ Scan(...any) error }) (*Alert, error) {
	var a Alert
	err := row.Scan(
		&a.ID, &a.OrgID, &a.RuleID, &a.RuleName,
		&a.Severity, &a.Message, &a.Context, &a.FiredAt,
		&a.ResolvedAt, &a.Notified,
		&a.Status, &a.AcknowledgedBy, &a.AcknowledgedAt, &a.MetricValue,
	)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

// scanAlertNoJoin scans an alert row that does NOT have rule_name (no JOIN).
func scanAlertNoJoin(row interface{ Scan(...any) error }) (*Alert, error) {
	var a Alert
	err := row.Scan(
		&a.ID, &a.OrgID, &a.RuleID,
		&a.Severity, &a.Message, &a.Context, &a.FiredAt,
		&a.ResolvedAt, &a.Notified,
		&a.Status, &a.AcknowledgedBy, &a.AcknowledgedAt, &a.MetricValue,
	)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

const alertColsJoined = `a.id, a.org_id, a.rule_id, r.name AS rule_name,
       a.severity, a.message, a.context, a.fired_at, a.resolved_at, a.notified,
       a.status, a.acknowledged_by, a.acknowledged_at, a.metric_value`

const alertColsNoJoin = `id, org_id, rule_id,
       severity, message, context, fired_at, resolved_at, notified,
       status, acknowledged_by, acknowledged_at, metric_value`

const listAlertsQuery = `SELECT ` + alertColsJoined + `
FROM alerts a JOIN alert_rules r ON r.id = a.rule_id
WHERE a.org_id = $1
  AND ($2::text IS NULL OR a.status = $2)
ORDER BY a.fired_at DESC
LIMIT $3 OFFSET $4`

func (q *Queries) ListAlerts(ctx context.Context, orgID uuid.UUID, status *string, limit, offset int32) ([]Alert, error) {
	rows, err := q.db.Query(ctx, listAlertsQuery,
		toPgtypeUUID(orgID), toPgtypeText(status), limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []Alert
	for rows.Next() {
		a, err := scanAlert(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *a)
	}
	return out, rows.Err()
}

const countAlertsQuery = `SELECT COUNT(*) FROM alerts WHERE org_id = $1 AND ($2::text IS NULL OR status = $2)`

func (q *Queries) CountAlerts(ctx context.Context, orgID uuid.UUID, status *string) (int64, error) {
	row := q.db.QueryRow(ctx, countAlertsQuery, toPgtypeUUID(orgID), toPgtypeText(status))
	var count int64
	return count, row.Scan(&count)
}

const createAlertQuery = `INSERT INTO alerts (org_id, rule_id, severity, message, context, metric_value)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING ` + alertColsNoJoin

func (q *Queries) CreateAlert(ctx context.Context,
	orgID, ruleID uuid.UUID, severity, message string, ctx_ []byte, metricValue float64,
) (*Alert, error) {
	row := q.db.QueryRow(ctx, createAlertQuery,
		toPgtypeUUID(orgID), toPgtypeUUID(ruleID),
		severity, message, ctx_,
		pgtype.Float8{Float64: metricValue, Valid: true},
	)
	return scanAlertNoJoin(row)
}

const getOpenAlertByRuleIDQuery = `SELECT ` + alertColsNoJoin + `
FROM alerts WHERE rule_id = $1 AND status = 'open' LIMIT 1`

func (q *Queries) GetOpenAlertByRuleID(ctx context.Context, ruleID uuid.UUID) (*Alert, error) {
	return scanAlertNoJoin(q.db.QueryRow(ctx, getOpenAlertByRuleIDQuery, toPgtypeUUID(ruleID)))
}

const updateAlertStatusQuery = `UPDATE alerts SET
    status          = $3,
    acknowledged_by = CASE WHEN $3 = 'acknowledged' THEN $4 ELSE acknowledged_by END,
    acknowledged_at = CASE WHEN $3 = 'acknowledged' THEN NOW() ELSE acknowledged_at END,
    resolved_at     = CASE WHEN $3 = 'resolved' THEN NOW() ELSE resolved_at END
WHERE id = $1 AND org_id = $2
RETURNING ` + alertColsNoJoin

func (q *Queries) UpdateAlertStatus(ctx context.Context,
	id, orgID uuid.UUID, status string, acknowledgedBy pgtype.UUID,
) (*Alert, error) {
	return scanAlertNoJoin(q.db.QueryRow(ctx, updateAlertStatusQuery,
		toPgtypeUUID(id), toPgtypeUUID(orgID), status, acknowledgedBy,
	))
}

const markAlertNotifiedQuery = `UPDATE alerts SET notified = TRUE WHERE id = $1`

func (q *Queries) MarkAlertNotified(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAlertNotifiedQuery, toPgtypeUUID(id))
	return err
}

const countScopeDriftEventsQuery = `
SELECT COUNT(*)
FROM audit_log
WHERE org_id = $1
  AND decision = 'escalated'
  AND timestamp >= NOW() - ($2 || ' minutes')::INTERVAL`

// CountScopeDriftEvents returns the number of escalated decisions in audit_log
// within the given window. Used by the alerting engine for scope_drift_count.
func (q *Queries) CountScopeDriftEvents(ctx context.Context, orgID uuid.UUID, windowMinutes int) (int64, error) {
	row := q.db.QueryRow(ctx, countScopeDriftEventsQuery,
		toPgtypeUUID(orgID),
		fmt.Sprintf("%d", windowMinutes),
	)
	var n int64
	return n, row.Scan(&n)
}
