// Code generated by sqlc from internal/store/query/approvals.sql. DO NOT EDIT directly.
// Re-generate: sqlc generate
package store

import (
	"context"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// approvalCols is the shared SELECT column list used by all approval queries.
const approvalCols = `id, org_id, agent_id, agent_name, tool_name, action, parameters,
    justification, risk_level, estimated_records, reversible, environment,
    data_types, policy_id, status, approved_by, decision_reason,
    decided_at, expires_at, created_at, gateway_session_id, gateway_node_address`

func scanApproval(row interface {
	Scan(dest ...any) error
}) (*ApprovalRequest, error) {
	var a ApprovalRequest
	err := row.Scan(
		&a.ID, &a.OrgID, &a.AgentID, &a.AgentName, &a.ToolName, &a.Action, &a.Parameters,
		&a.Justification, &a.RiskLevel, &a.EstimatedRecords, &a.Reversible, &a.Environment,
		&a.DataTypes, &a.PolicyID, &a.Status, &a.ApprovedBy, &a.DecisionReason,
		&a.DecidedAt, &a.ExpiresAt, &a.CreatedAt, &a.GatewaySessionID, &a.GatewayNodeAddress,
	)
	if err != nil {
		return nil, err
	}
	return &a, nil
}

// NotifyApprovalDecision sends NOTIFY on the approval_decision channel so
// the gateway can resume or cancel the held tool call session.
func (q *Queries) NotifyApprovalDecision(ctx context.Context, approvalID uuid.UUID) error {
	payload := fmt.Sprintf(`{"approval_id":"%s"}`, approvalID.String())
	_, err := q.db.Exec(ctx, "SELECT pg_notify($1, $2)", "approval_decision", payload)
	return err
}

type ListApprovalsParams struct {
	OrgID    uuid.UUID
	Status   *string
	AgentID  *uuid.UUID
	From     *time.Time
	To       *time.Time
	Limit    int32
	Offset   int32
}

const listApprovalsQuery = `-- name: ListApprovals :many
SELECT ` + approvalCols + `
FROM approval_requests
WHERE org_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR agent_id = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)
ORDER BY created_at DESC
LIMIT $6 OFFSET $7`

func (q *Queries) ListApprovals(ctx context.Context, p ListApprovalsParams) ([]ApprovalRequest, error) {
	rows, err := q.db.Query(ctx, listApprovalsQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.Status),
		toPgtypeUUIDPtr(p.AgentID),
		toPgtypeTimestamptz(p.From),
		toPgtypeTimestamptz(p.To),
		p.Limit,
		p.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []ApprovalRequest
	for rows.Next() {
		a, err := scanApproval(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, *a)
	}
	return out, rows.Err()
}

const countApprovalsQuery = `-- name: CountApprovals :one
SELECT COUNT(*) FROM approval_requests
WHERE org_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::uuid IS NULL OR agent_id = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4)
  AND ($5::timestamptz IS NULL OR created_at <= $5)`

func (q *Queries) CountApprovals(ctx context.Context, p ListApprovalsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApprovalsQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.Status),
		toPgtypeUUIDPtr(p.AgentID),
		toPgtypeTimestamptz(p.From),
		toPgtypeTimestamptz(p.To),
	)
	var count int64
	return count, row.Scan(&count)
}

const getApprovalQuery = `-- name: GetApproval :one
SELECT ` + approvalCols + `
FROM approval_requests
WHERE id = $1 AND org_id = $2
LIMIT 1`

func (q *Queries) GetApproval(ctx context.Context, id, orgID uuid.UUID) (*ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, getApprovalQuery, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return scanApproval(row)
}

type CreateApprovalParams struct {
	OrgID              uuid.UUID
	AgentID            uuid.UUID
	AgentName          string
	ToolName           string
	Action             string
	Parameters         []byte
	Justification      string
	RiskLevel          string
	EstimatedRecords   pgtype.Int4
	Reversible         pgtype.Bool
	Environment        pgtype.Text
	DataTypes          []string
	PolicyID           pgtype.UUID
	ExpiresAt          time.Time
	GatewaySessionID   string
	GatewayNodeAddress string
}

const createApprovalQuery = `-- name: CreateApproval :one
INSERT INTO approval_requests (
    org_id, agent_id, agent_name, tool_name, action, parameters,
    justification, risk_level, estimated_records, reversible, environment,
    data_types, policy_id, expires_at, gateway_session_id, gateway_node_address
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15, $16
)
RETURNING ` + approvalCols

func (q *Queries) CreateApproval(ctx context.Context, p CreateApprovalParams) (*ApprovalRequest, error) {
	dataTypes := p.DataTypes
	if dataTypes == nil {
		dataTypes = []string{}
	}
	row := q.db.QueryRow(ctx, createApprovalQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeUUID(p.AgentID),
		p.AgentName,
		p.ToolName,
		p.Action,
		p.Parameters,
		p.Justification,
		p.RiskLevel,
		p.EstimatedRecords,
		p.Reversible,
		p.Environment,
		dataTypes,
		p.PolicyID,
		pgtype.Timestamptz{Time: p.ExpiresAt, Valid: true},
		p.GatewaySessionID,
		p.GatewayNodeAddress,
	)
	return scanApproval(row)
}

type DecideApprovalParams struct {
	ID             uuid.UUID
	OrgID          uuid.UUID
	Status         string     // "approved" or "denied"
	ApprovedBy     pgtype.UUID
	DecisionReason pgtype.Text
}

const decideApprovalQuery = `-- name: DecideApproval :one
UPDATE approval_requests SET
    status          = $3,
    approved_by     = $4,
    decision_reason = $5,
    decided_at      = NOW()
WHERE id = $1 AND org_id = $2 AND status = 'pending'
RETURNING ` + approvalCols

func (q *Queries) DecideApproval(ctx context.Context, p DecideApprovalParams) (*ApprovalRequest, error) {
	row := q.db.QueryRow(ctx, decideApprovalQuery,
		toPgtypeUUID(p.ID),
		toPgtypeUUID(p.OrgID),
		p.Status,
		p.ApprovedBy,
		p.DecisionReason,
	)
	return scanApproval(row)
}

// toPgtypeUUIDPtr converts *uuid.UUID to pgtype.UUID (NULL when nil).
func toPgtypeUUIDPtr(id *uuid.UUID) pgtype.UUID {
	if id == nil {
		return pgtype.UUID{Valid: false}
	}
	return pgtype.UUID{Bytes: *id, Valid: true}
}

// toPgtypeTimestamptz converts *time.Time to pgtype.Timestamptz (NULL when nil).
func toPgtypeTimestamptz(t *time.Time) pgtype.Timestamptz {
	if t == nil {
		return pgtype.Timestamptz{Valid: false}
	}
	return pgtype.Timestamptz{Time: *t, Valid: true}
}
