// Code generated by sqlc from internal/store/query/audit.sql. DO NOT EDIT directly.
package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ListAuditParams struct {
	OrgID     uuid.UUID
	AgentName *string
	ToolName  *string
	Decision  *string
	From      *time.Time
	To        *time.Time
	Limit     int32
	Offset    int32
}

const listAuditQuery = `-- name: ListAudit :many
SELECT
    id, org_id, agent_id, agent_name, tool_name, action, parameters, decision,
    policy_id, approval_id, approved_by, latency_ms, token_in, token_out,
    timestamp, prev_hash, hash, data_handling_designation, redacted_count
FROM audit_log
WHERE org_id = $1
  AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR decision = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
ORDER BY timestamp DESC
LIMIT $7 OFFSET $8
`

func (q *Queries) ListAudit(ctx context.Context, p ListAuditParams) ([]AuditEntry, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	rows, err := q.db.Query(ctx, listAuditQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
		p.Limit,
		p.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []AuditEntry
	for rows.Next() {
		var e AuditEntry
		if err := rows.Scan(
			&e.ID, &e.OrgID, &e.AgentID, &e.AgentName, &e.ToolName, &e.Action,
			&e.Parameters, &e.Decision, &e.PolicyID, &e.ApprovalID, &e.ApprovedBy,
			&e.LatencyMS, &e.TokenIn, &e.TokenOut, &e.Timestamp, &e.PrevHash, &e.Hash,
			&e.DataHandling, &e.RedactedCount,
		); err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, rows.Err()
}

const countAuditQuery = `-- name: CountAudit :one
SELECT COUNT(*) FROM audit_log
WHERE org_id = $1
  AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR decision = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
`

func (q *Queries) CountAudit(ctx context.Context, p ListAuditParams) (int64, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	row := q.db.QueryRow(ctx, countAuditQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
	)
	var count int64
	return count, row.Scan(&count)
}

// ExportAuditMaxRows is the hard cap on audit export rows. The handler rejects
// an over-limit export before writing a response, rather than silently handing
// a compliance user a partial CSV.
const ExportAuditMaxRows = 10_000

// ExportAuditMaxFieldBytes limits one gateway-controlled text cell before an
// export scans it into API process memory. The aggregate CSV ceiling is
// enforced by the API; this lower per-cell limit keeps a single malformed
// audit value from defeating that aggregate bound during pgx scanning.
const ExportAuditMaxFieldBytes = 1 << 20

const exportAuditQuery = `-- name: ExportAudit :many
SELECT
    id, agent_id, agent_name, tool_name, action, decision, latency_ms,
    token_in, token_out, timestamp, hash
FROM audit_log
WHERE org_id = $1
  AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR decision = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
ORDER BY timestamp DESC
LIMIT $7`

const exportAuditStatsQuery = `-- name: ExportAuditStats :one
SELECT
  COUNT(*)::int,
  COALESCE(MAX(GREATEST(
    COALESCE(octet_length(agent_name), 0),
    COALESCE(octet_length(tool_name), 0),
    COALESCE(octet_length(action), 0),
    COALESCE(octet_length(decision), 0),
    COALESCE(octet_length(hash), 0)
  )), 0)::int,
  COALESCE(SUM(
    2 * (
      COALESCE(octet_length(agent_name), 0) +
      COALESCE(octet_length(tool_name), 0) +
      COALESCE(octet_length(action), 0) +
      COALESCE(octet_length(decision), 0) +
      COALESCE(octet_length(hash), 0)
    ) + 256
  ), 0)::bigint
FROM (
  SELECT agent_name, tool_name, action, decision, hash
  FROM audit_log
  WHERE org_id = $1
    AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
    AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
    AND ($4::text IS NULL OR decision = $4)
    AND ($5::timestamptz IS NULL OR timestamp >= $5)
    AND ($6::timestamptz IS NULL OR timestamp <= $6)
  ORDER BY timestamp DESC
  LIMIT $7
) AS export_rows`

// AuditExportRow is a minimal audit row for CSV export (no parameters JSONB).
type AuditExportRow struct {
	ID        uuid.UUID
	AgentID   pgtype.UUID
	AgentName string
	ToolName  string
	Action    string
	Decision  string
	LatencyMS pgtype.Int4
	TokenIn   pgtype.Int4
	TokenOut  pgtype.Int4
	Timestamp time.Time
	Hash      string
}

// AuditExportStats is a preflight result. EstimatedBytes deliberately assumes
// every text byte must be quoted and escaped, then leaves 256 bytes for each
// CSV row's fixed fields. It is therefore a conservative upper bound for the
// CSV writer before gateway-controlled text is scanned into API memory.
type AuditExportStats struct {
	Rows           int
	MaxFieldBytes  int
	EstimatedBytes int64
}

func (q *Queries) AuditExportStats(ctx context.Context, p ListAuditParams) (AuditExportStats, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	// Fetch one extra row so callers can reject, rather than truncate, an
	// over-limit export before transferring unbounded text values.
	limit := int32(ExportAuditMaxRows + 1)
	var stats AuditExportStats
	err := q.db.QueryRow(ctx, exportAuditStatsQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
		limit,
	).Scan(&stats.Rows, &stats.MaxFieldBytes, &stats.EstimatedBytes)
	return stats, err
}

// ExportAudit streams rows to visit. Callers must preflight with
// AuditExportStats in the same read-only repeatable-read transaction, so this
// function never accumulates a complete CSV-sized row slice in API memory.
func (q *Queries) ExportAudit(ctx context.Context, p ListAuditParams, visit func(AuditExportRow) error) error {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	rows, err := q.db.Query(ctx, exportAuditQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
		int32(ExportAuditMaxRows),
	)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		var e AuditExportRow
		if err := rows.Scan(
			&e.ID, &e.AgentID, &e.AgentName, &e.ToolName, &e.Action, &e.Decision,
			&e.LatencyMS, &e.TokenIn, &e.TokenOut, &e.Timestamp, &e.Hash,
		); err != nil {
			return err
		}
		if err := visit(e); err != nil {
			return err
		}
	}
	return rows.Err()
}
