// Code generated by sqlc from internal/store/query/audit.sql. DO NOT EDIT directly.
package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ListAuditParams struct {
	OrgID     uuid.UUID
	AgentName *string
	ToolName  *string
	Decision  *string
	From      *time.Time
	To        *time.Time
	Limit     int32
	Offset    int32
}

const listAuditQuery = `-- name: ListAudit :many
SELECT
    id, org_id, agent_id, agent_name, tool_name, action, parameters, decision,
    policy_id, approval_id, approved_by, latency_ms, token_in, token_out,
    timestamp, prev_hash, hash
FROM audit_log
WHERE org_id = $1
  AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR decision = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
ORDER BY timestamp DESC
LIMIT $7 OFFSET $8
`

func (q *Queries) ListAudit(ctx context.Context, p ListAuditParams) ([]AuditEntry, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	rows, err := q.db.Query(ctx, listAuditQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
		p.Limit,
		p.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []AuditEntry
	for rows.Next() {
		var e AuditEntry
		if err := rows.Scan(
			&e.ID, &e.OrgID, &e.AgentID, &e.AgentName, &e.ToolName, &e.Action,
			&e.Parameters, &e.Decision, &e.PolicyID, &e.ApprovalID, &e.ApprovedBy,
			&e.LatencyMS, &e.TokenIn, &e.TokenOut, &e.Timestamp, &e.PrevHash, &e.Hash,
		); err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, rows.Err()
}

const countAuditQuery = `-- name: CountAudit :one
SELECT COUNT(*) FROM audit_log
WHERE org_id = $1
  AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR decision = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
`

func (q *Queries) CountAudit(ctx context.Context, p ListAuditParams) (int64, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	row := q.db.QueryRow(ctx, countAuditQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
	)
	var count int64
	return count, row.Scan(&count)
}

// ExportAuditMaxRows is the hard cap on audit export rows to prevent OOM.
const ExportAuditMaxRows = 100_000

const exportAuditQuery = `-- name: ExportAudit :many
SELECT
    id, org_id, agent_id, agent_name, tool_name, action, decision,
    latency_ms, timestamp, prev_hash, hash
FROM audit_log
WHERE org_id = $1
  AND ($2::text IS NULL OR agent_name ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR tool_name  ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR decision = $4)
  AND ($5::timestamptz IS NULL OR timestamp >= $5)
  AND ($6::timestamptz IS NULL OR timestamp <= $6)
ORDER BY timestamp DESC
LIMIT $7`

// AuditExportRow is a minimal audit row for CSV export (no parameters JSONB).
type AuditExportRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	AgentID   pgtype.UUID
	AgentName string
	ToolName  string
	Action    string
	Decision  string
	LatencyMS pgtype.Int4
	Timestamp time.Time
	PrevHash  string
	Hash      string
}

func (q *Queries) ExportAudit(ctx context.Context, p ListAuditParams) ([]AuditExportRow, bool, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	// Fetch one extra row to detect truncation.
	limit := int32(ExportAuditMaxRows + 1)

	rows, err := q.db.Query(ctx, exportAuditQuery,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.AgentName),
		toPgtypeText(p.ToolName),
		toPgtypeText(p.Decision),
		toTsArg(p.From),
		toTsArg(p.To),
		limit,
	)
	if err != nil {
		return nil, false, err
	}
	defer rows.Close()

	var out []AuditExportRow
	for rows.Next() {
		var e AuditExportRow
		if err := rows.Scan(
			&e.ID, &e.OrgID, &e.AgentID, &e.AgentName, &e.ToolName, &e.Action,
			&e.Decision, &e.LatencyMS, &e.Timestamp, &e.PrevHash, &e.Hash,
		); err != nil {
			return nil, false, err
		}
		out = append(out, e)
	}
	if err := rows.Err(); err != nil {
		return nil, false, err
	}

	truncated := false
	if len(out) > ExportAuditMaxRows {
		out = out[:ExportAuditMaxRows]
		truncated = true
	}
	return out, truncated, nil
}
