// Code generated by sqlc from internal/store/query/auth.sql. DO NOT EDIT directly.
// Re-generate: sqlc generate
package store

import (
	"context"
	"crypto/sha256"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, org_id, email, name, password_hash, role
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, toPgtypeUUID(id))
	var u User
	err := row.Scan(&u.ID, &u.OrgID, &u.Email, &u.Name, &u.PasswordHash, &u.Role)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, org_id, email, name, password_hash, role
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var u User
	err := row.Scan(&u.ID, &u.OrgID, &u.Email, &u.Name, &u.PasswordHash, &u.Role)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

const createRefreshToken = `-- name: CreateRefreshToken :one
INSERT INTO refresh_tokens (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, expires_at, created_at, revoked
`

func (q *Queries) CreateRefreshToken(ctx context.Context, userID uuid.UUID, tokenHash string, expiresAt time.Time) (*RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, toPgtypeUUID(userID), tokenHash, pgtype.Timestamptz{Time: expiresAt, Valid: true})
	var rt RefreshToken
	var createdAt time.Time
	err := row.Scan(&rt.ID, &rt.UserID, &rt.TokenHash, &rt.ExpiresAt, &createdAt, &rt.Revoked)
	if err != nil {
		return nil, err
	}
	return &rt, nil
}

const getRefreshToken = `-- name: GetRefreshToken :one
SELECT id, user_id, token_hash, expires_at, revoked
FROM refresh_tokens
WHERE token_hash = $1 AND revoked = FALSE AND expires_at > NOW()
LIMIT 1
`

func (q *Queries) GetRefreshToken(ctx context.Context, rawToken string) (*RefreshToken, error) {
	hash := fmt.Sprintf("%x", sha256.Sum256([]byte(rawToken)))
	row := q.db.QueryRow(ctx, getRefreshToken, hash)
	var rt RefreshToken
	err := row.Scan(&rt.ID, &rt.UserID, &rt.TokenHash, &rt.ExpiresAt, &rt.Revoked)
	if err != nil {
		return nil, err
	}
	return &rt, nil
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked = TRUE WHERE id = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, toPgtypeUUID(id))
	return err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, org_id, name, prefix, scopes, created_by, created_at, last_used, revoked
FROM api_keys
WHERE org_id = $1 AND revoked = FALSE
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, orgID uuid.UUID) ([]APIKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, toPgtypeUUID(orgID))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var keys []APIKey
	for rows.Next() {
		var k APIKey
		if err := rows.Scan(
			&k.ID, &k.OrgID, &k.Name, &k.Prefix, &k.Scopes,
			&k.CreatedBy, &k.CreatedAt, &k.LastUsed, &k.Revoked,
		); err != nil {
			return nil, err
		}
		keys = append(keys, k)
	}
	return keys, rows.Err()
}

type CreateAPIKeyParams struct {
	OrgID     uuid.UUID
	Name      string
	KeyHash   string
	Prefix    string
	Scopes    []string
	CreatedBy pgtype.UUID
}

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (org_id, name, key_hash, prefix, scopes, created_by)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, org_id, name, prefix, scopes, created_by, created_at, last_used, revoked
`

func (q *Queries) CreateAPIKey(ctx context.Context, p CreateAPIKeyParams) (*APIKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		toPgtypeUUID(p.OrgID), p.Name, p.KeyHash, p.Prefix, p.Scopes, p.CreatedBy,
	)
	var k APIKey
	err := row.Scan(
		&k.ID, &k.OrgID, &k.Name, &k.Prefix, &k.Scopes,
		&k.CreatedBy, &k.CreatedAt, &k.LastUsed, &k.Revoked,
	)
	if err != nil {
		return nil, err
	}
	return &k, nil
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET revoked = TRUE WHERE id = $1 AND org_id = $2
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, org_id, name, prefix, scopes, created_by, created_at, last_used, revoked
FROM api_keys
WHERE key_hash = $1 AND revoked = FALSE
LIMIT 1
`

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (*APIKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var k APIKey
	err := row.Scan(
		&k.ID, &k.OrgID, &k.Name, &k.Prefix, &k.Scopes,
		&k.CreatedBy, &k.CreatedAt, &k.LastUsed, &k.Revoked,
	)
	if err != nil {
		return nil, err
	}
	return &k, nil
}
