// Code generated by hand from internal/store/query/endpoints.sql. DO NOT run sqlc.
package store

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgtype"
)

// DiscoveredEndpoint mirrors the discovered_endpoints table.
type DiscoveredEndpoint struct {
	ID         uuid.UUID
	OrgID      uuid.UUID
	SourceHost string
	Method     string
	Host       string
	Path       string
	Port       pgtype.Int4
	TLS        bool
	Tags       []string
	RawHeaders []byte // JSONB
	HitCount   int32
	LastSeen   pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

// RawHeadersMap decodes the JSONB raw_headers into a Go map.
func (e *DiscoveredEndpoint) RawHeadersMap() map[string]string {
	out := make(map[string]string)
	if len(e.RawHeaders) > 0 {
		_ = json.Unmarshal(e.RawHeaders, &out)
	}
	return out
}

// UpsertEndpointParams holds parameters for UpsertEndpoint.
type UpsertEndpointParams struct {
	OrgID      uuid.UUID
	SourceHost string
	Method     string
	Host       string
	Path       string
	Port       pgtype.Int4
	TLS        bool
	Tags       []string
	RawHeaders []byte
}

const upsertEndpointSQL = `
INSERT INTO discovered_endpoints
    (org_id, source_host, method, host, path, port, tls, tags, raw_headers, last_seen)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, NOW())
ON CONFLICT (org_id, source_host, method, host, path) DO UPDATE SET
    last_seen   = NOW(),
    hit_count   = discovered_endpoints.hit_count + 1,
    tags        = EXCLUDED.tags,
    raw_headers = EXCLUDED.raw_headers`

func (q *Queries) UpsertEndpoint(ctx context.Context, p UpsertEndpointParams) error {
	tags := p.Tags
	if tags == nil {
		tags = []string{}
	}
	rawHeaders := p.RawHeaders
	if rawHeaders == nil {
		rawHeaders = []byte("{}")
	}
	_, err := q.db.Exec(ctx, upsertEndpointSQL,
		toPgtypeUUID(p.OrgID),
		p.SourceHost,
		p.Method,
		p.Host,
		p.Path,
		p.Port,
		p.TLS,
		tags,
		rawHeaders,
	)
	return err
}

// ListEndpointsParams holds filter + pagination for ListEndpoints.
type ListEndpointsParams struct {
	OrgID      uuid.UUID
	Host       *string
	SourceHost *string
	Tag        *string
	Limit      int32
	Offset     int32
}

const listEndpointsSQL = `
SELECT id, org_id, source_host, method, host, path, port, tls, tags,
       raw_headers, hit_count, last_seen, created_at
FROM discovered_endpoints
WHERE org_id = $1
  AND ($2::text IS NULL OR host        ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR source_host ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR $4 = ANY(tags))
ORDER BY last_seen DESC
LIMIT $5 OFFSET $6`

func (q *Queries) ListEndpoints(ctx context.Context, p ListEndpointsParams) ([]DiscoveredEndpoint, error) {
	rows, err := q.db.Query(ctx, listEndpointsSQL,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.Host),
		toPgtypeText(p.SourceHost),
		toPgtypeText(p.Tag),
		p.Limit,
		p.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []DiscoveredEndpoint
	for rows.Next() {
		e, err := scanEndpoint(rows)
		if err != nil {
			return nil, err
		}
		out = append(out, e)
	}
	return out, rows.Err()
}

const countEndpointsSQL = `
SELECT COUNT(*) FROM discovered_endpoints
WHERE org_id = $1
  AND ($2::text IS NULL OR host        ILIKE '%' || $2 || '%')
  AND ($3::text IS NULL OR source_host ILIKE '%' || $3 || '%')
  AND ($4::text IS NULL OR $4 = ANY(tags))`

func (q *Queries) CountEndpoints(ctx context.Context, p ListEndpointsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEndpointsSQL,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.Host),
		toPgtypeText(p.SourceHost),
		toPgtypeText(p.Tag),
	)
	var n int64
	return n, row.Scan(&n)
}

const getEndpointSQL = `
SELECT id, org_id, source_host, method, host, path, port, tls, tags,
       raw_headers, hit_count, last_seen, created_at
FROM discovered_endpoints
WHERE id = $1 AND org_id = $2`

func (q *Queries) GetEndpoint(ctx context.Context, id, orgID uuid.UUID) (*DiscoveredEndpoint, error) {
	row := q.db.QueryRow(ctx, getEndpointSQL,
		toPgtypeUUID(id),
		toPgtypeUUID(orgID),
	)
	e, err := scanEndpointRow(row)
	if err != nil {
		return nil, err
	}
	return &e, nil
}

// scanEndpoint scans a DiscoveredEndpoint from a pgx.Rows cursor.
func scanEndpoint(rows pgx.Rows) (DiscoveredEndpoint, error) {
	var e DiscoveredEndpoint
	var orgID pgtype.UUID
	var id pgtype.UUID
	err := rows.Scan(
		&id, &orgID, &e.SourceHost, &e.Method, &e.Host, &e.Path,
		&e.Port, &e.TLS, &e.Tags, &e.RawHeaders,
		&e.HitCount, &e.LastSeen, &e.CreatedAt,
	)
	if err != nil {
		return e, err
	}
	e.ID = uuid.UUID(id.Bytes)
	e.OrgID = uuid.UUID(orgID.Bytes)
	return e, nil
}

// scanEndpointRow scans a DiscoveredEndpoint from a single pgx.Row.
func scanEndpointRow(row pgx.Row) (DiscoveredEndpoint, error) {
	var e DiscoveredEndpoint
	var orgID pgtype.UUID
	var id pgtype.UUID
	err := row.Scan(
		&id, &orgID, &e.SourceHost, &e.Method, &e.Host, &e.Path,
		&e.Port, &e.TLS, &e.Tags, &e.RawHeaders,
		&e.HitCount, &e.LastSeen, &e.CreatedAt,
	)
	if err != nil {
		return e, err
	}
	e.ID = uuid.UUID(id.Bytes)
	e.OrgID = uuid.UUID(orgID.Bytes)
	return e, nil
}
