// Code generated by hand from internal/store/query/model_pricing.sql. DO NOT run sqlc.
//
// Admin CRUD for the model_pricing table (B-112). A separate file from
// token_usage.sql.go's GetModelPricing on purpose -- that function is
// tightly coupled to the token-usage ingestion cost formula (B-111's
// query-time design means it never needs the 3 cache-rate columns), while
// this file is a genuinely different concern: an operator managing the
// pricing catalog itself.
package store

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

// ModelPricingRow is one full model_pricing row, including B-111's 3
// cache-rate columns as pgtype.Float8 -- nullable, since only claude-*
// models need them (a non-Claude model's rows never populate the
// cache-token counters those rates would price).
type ModelPricingRow struct {
	Model                 string
	CostPer1kIn           float64
	CostPer1kOut          float64
	CostPer1kCacheWrite5m pgtype.Float8
	CostPer1kCacheWrite1h pgtype.Float8
	CostPer1kCacheRead    pgtype.Float8
	UpdatedAt             time.Time
}

const listModelPricingSQL = `
SELECT model, cost_per_1k_in, cost_per_1k_out, cost_per_1k_cache_write_5m, cost_per_1k_cache_write_1h, cost_per_1k_cache_read, updated_at
FROM model_pricing
ORDER BY model`

// ListModelPricing returns every model_pricing row -- this table is global
// (no org_id column), so there is no org-scoping parameter here.
func (q *Queries) ListModelPricing(ctx context.Context) ([]ModelPricingRow, error) {
	rows, err := q.db.Query(ctx, listModelPricingSQL)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []ModelPricingRow
	for rows.Next() {
		var m ModelPricingRow
		if err := rows.Scan(
			&m.Model, &m.CostPer1kIn, &m.CostPer1kOut,
			&m.CostPer1kCacheWrite5m, &m.CostPer1kCacheWrite1h, &m.CostPer1kCacheRead,
			&m.UpdatedAt,
		); err != nil {
			return nil, err
		}
		out = append(out, m)
	}
	return out, rows.Err()
}

// CreateModelPricingParams holds parameters for CreateModelPricing.
type CreateModelPricingParams struct {
	Model                 string
	CostPer1kIn           float64
	CostPer1kOut          float64
	CostPer1kCacheWrite5m pgtype.Float8 // Valid:false -> NULL, no rate configured
	CostPer1kCacheWrite1h pgtype.Float8
	CostPer1kCacheRead    pgtype.Float8
}

const createModelPricingSQL = `
INSERT INTO model_pricing (model, cost_per_1k_in, cost_per_1k_out, cost_per_1k_cache_write_5m, cost_per_1k_cache_write_1h, cost_per_1k_cache_read)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING model, cost_per_1k_in, cost_per_1k_out, cost_per_1k_cache_write_5m, cost_per_1k_cache_write_1h, cost_per_1k_cache_read, updated_at`

// CreateModelPricing inserts a new model's pricing row. Returns a Postgres
// unique-violation error (SQLSTATE 23505, model is the PK) if the model
// already has a row -- callers should map that to a 409, not a 500.
func (q *Queries) CreateModelPricing(ctx context.Context, p CreateModelPricingParams) (ModelPricingRow, error) {
	row := q.db.QueryRow(ctx, createModelPricingSQL,
		p.Model, p.CostPer1kIn, p.CostPer1kOut,
		p.CostPer1kCacheWrite5m, p.CostPer1kCacheWrite1h, p.CostPer1kCacheRead,
	)
	var m ModelPricingRow
	err := row.Scan(
		&m.Model, &m.CostPer1kIn, &m.CostPer1kOut,
		&m.CostPer1kCacheWrite5m, &m.CostPer1kCacheWrite1h, &m.CostPer1kCacheRead,
		&m.UpdatedAt,
	)
	return m, err
}

// UpdateModelPricingParams holds parameters for UpdateModelPricing.
// Invalid (zero-value) pgtype.Float8 fields leave that column unchanged --
// PATCH semantics via COALESCE, mirroring agents.sql.go's UpdateAgent.
type UpdateModelPricingParams struct {
	Model                 string
	CostPer1kIn           pgtype.Float8
	CostPer1kOut          pgtype.Float8
	CostPer1kCacheWrite5m pgtype.Float8
	CostPer1kCacheWrite1h pgtype.Float8
	CostPer1kCacheRead    pgtype.Float8
}

const updateModelPricingSQL = `
UPDATE model_pricing SET
    cost_per_1k_in             = COALESCE($2, cost_per_1k_in),
    cost_per_1k_out            = COALESCE($3, cost_per_1k_out),
    cost_per_1k_cache_write_5m = COALESCE($4, cost_per_1k_cache_write_5m),
    cost_per_1k_cache_write_1h = COALESCE($5, cost_per_1k_cache_write_1h),
    cost_per_1k_cache_read     = COALESCE($6, cost_per_1k_cache_read),
    updated_at                 = NOW()
WHERE model = $1
RETURNING model, cost_per_1k_in, cost_per_1k_out, cost_per_1k_cache_write_5m, cost_per_1k_cache_write_1h, cost_per_1k_cache_read, updated_at`

// UpdateModelPricing returns pgx.ErrNoRows if the model has no existing row.
func (q *Queries) UpdateModelPricing(ctx context.Context, p UpdateModelPricingParams) (ModelPricingRow, error) {
	row := q.db.QueryRow(ctx, updateModelPricingSQL,
		p.Model, p.CostPer1kIn, p.CostPer1kOut,
		p.CostPer1kCacheWrite5m, p.CostPer1kCacheWrite1h, p.CostPer1kCacheRead,
	)
	var m ModelPricingRow
	err := row.Scan(
		&m.Model, &m.CostPer1kIn, &m.CostPer1kOut,
		&m.CostPer1kCacheWrite5m, &m.CostPer1kCacheWrite1h, &m.CostPer1kCacheRead,
		&m.UpdatedAt,
	)
	return m, err
}

const deleteModelPricingSQL = `DELETE FROM model_pricing WHERE model = $1`

// DeleteModelPricing returns the number of rows deleted (0 or 1) -- callers
// map 0 to a 404, since model is the table's PK.
func (q *Queries) DeleteModelPricing(ctx context.Context, model string) (int64, error) {
	tag, err := q.db.Exec(ctx, deleteModelPricingSQL, model)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}
