// Code generated by hand from internal/store/query/paste_events.sql. DO NOT run sqlc.
package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// PasteEventInput is one event to be written by BatchInsertPasteEvents.
// Deliberately has no field capable of carrying the pasted text itself --
// only coarse indicators (length, hash) ever reach this type.
type PasteEventInput struct {
	OrgID             uuid.UUID
	SourceEndpointID  uuid.UUID
	DestinationDomain string
	ContentLength     *int32
	ContentHash       *string
	OSUsername        *string
	OccurredAt        time.Time
}

const batchInsertPasteEventsSQL = `
INSERT INTO paste_events
    (org_id, source_endpoint_id, destination_domain, content_length, content_hash, os_username, occurred_at)
SELECT * FROM unnest(
    $1::uuid[], $2::uuid[], $3::text[], $4::int[], $5::text[], $6::text[], $7::timestamptz[]
)`

// BatchInsertPasteEvents writes a batch of paste events in a single
// multi-row INSERT (one round trip regardless of batch size), via
// unnest() over parallel arrays -- not N sequential Exec calls. Append-only:
// no ON CONFLICT, no dedup/collapsing. Returns the number of rows written.
func (q *Queries) BatchInsertPasteEvents(ctx context.Context, events []PasteEventInput) (int64, error) {
	if len(events) == 0 {
		return 0, nil
	}

	orgIDs := make([]string, len(events))
	endpointIDs := make([]string, len(events))
	domains := make([]string, len(events))
	contentLengths := make([]*int32, len(events))
	contentHashes := make([]*string, len(events))
	osUsernames := make([]*string, len(events))
	occurredAts := make([]time.Time, len(events))

	for i, e := range events {
		orgIDs[i] = e.OrgID.String()
		endpointIDs[i] = e.SourceEndpointID.String()
		domains[i] = e.DestinationDomain
		contentLengths[i] = e.ContentLength
		contentHashes[i] = e.ContentHash
		osUsernames[i] = e.OSUsername
		occurredAts[i] = e.OccurredAt
	}

	tag, err := q.db.Exec(ctx, batchInsertPasteEventsSQL,
		orgIDs, endpointIDs, domains, contentLengths, contentHashes, osUsernames, occurredAts,
	)
	if err != nil {
		return 0, err
	}
	return tag.RowsAffected(), nil
}

// ResolvePasteSourceEndpointParams holds parameters for ResolvePasteSourceEndpoint.
type ResolvePasteSourceEndpointParams struct {
	OrgID    uuid.UUID
	AgentID  string
	Hostname string
}

const resolvePasteSourceEndpointSQL = `
INSERT INTO endpoints (org_id, agent_id, hostname, last_seen)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (org_id, agent_id) DO UPDATE SET
    last_seen = NOW()
RETURNING id`

// ResolvePasteSourceEndpoint finds or creates the endpoints row identified
// by (org_id, agent_id) and returns its UUID, for use as paste_events.
// source_endpoint_id.
//
// Deliberately NOT UpsertAgentEndpoint (used by the full agent-scan
// ingestion pipeline in ingest.go): that function unconditionally
// overwrites hostname/agent_version/os_info on every call. A paste event
// only ever carries a hostname, never agent_version/os_info -- reusing
// UpsertAgentEndpoint here would silently blank out richer metadata
// already collected by the full eami-agent scanner every time a paste
// event arrives for the same machine. This lighter upsert only refreshes
// last_seen on conflict, and leaves hostname/agent_version/os_info exactly
// as first set (by whichever pipeline -- full scan or paste event --
// reported this agent_id first).
func (q *Queries) ResolvePasteSourceEndpoint(ctx context.Context, p ResolvePasteSourceEndpointParams) (uuid.UUID, error) {
	var id pgtype.UUID
	if err := q.db.QueryRow(ctx, resolvePasteSourceEndpointSQL,
		toPgtypeUUID(p.OrgID), p.AgentID, p.Hostname,
	).Scan(&id); err != nil {
		return uuid.Nil, err
	}
	return uuid.UUID(id.Bytes), nil
}

// ── Read path (B-038): admin UI over captured paste events ────────────────
//
// paste_events has no update/delete path anywhere in this codebase
// (append-only, per its own schema comment) -- these are the first reads
// of this table outside a test/seed script.

// PasteEvent is one row read back from paste_events.
type PasteEvent struct {
	ID                uuid.UUID
	OrgID             uuid.UUID
	SourceEndpointID  uuid.UUID
	DestinationDomain string
	ContentLength     pgtype.Int4
	ContentHash       pgtype.Text
	OSUsername        pgtype.Text
	OccurredAt        time.Time
	ReceivedAt        time.Time
}

// ListPasteEventsParams filters + paginates ListPasteEvents/CountPasteEvents.
// Domain/From/To are all optional, same "nil means unfiltered" convention
// as ListAuditParams.
type ListPasteEventsParams struct {
	OrgID  uuid.UUID
	Domain *string
	From   *time.Time
	To     *time.Time
	Limit  int32
	Offset int32
}

// listPasteEventsWhereSQL is shared between ListPasteEvents and
// CountPasteEvents so the two can never drift out of sync with each
// other (a paginated list and its count must agree on which rows match).
//
// $1=org_id $2=domain $3=from $4=to. Deliberately matches
// idx_paste_events_org (org_id, occurred_at DESC) when domain is omitted,
// and idx_paste_events_org_domain (org_id, destination_domain,
// occurred_at DESC) when it's supplied -- see paste_events_test.go's
// EXPLAIN ANALYZE tests for both cases.
const listPasteEventsWhereSQL = `
WHERE org_id = $1
  AND ($2::text IS NULL OR destination_domain = $2)
  AND ($3::timestamptz IS NULL OR occurred_at >= $3)
  AND ($4::timestamptz IS NULL OR occurred_at <= $4)`

const listPasteEventsSQL = `
SELECT id, org_id, source_endpoint_id, destination_domain, content_length, content_hash, os_username, occurred_at, received_at
FROM paste_events` + listPasteEventsWhereSQL + `
ORDER BY occurred_at DESC
LIMIT $5 OFFSET $6`

// ListPasteEvents returns one page of paste_events rows, newest first.
func (q *Queries) ListPasteEvents(ctx context.Context, p ListPasteEventsParams) ([]PasteEvent, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	rows, err := q.db.Query(ctx, listPasteEventsSQL,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.Domain),
		toTsArg(p.From),
		toTsArg(p.To),
		p.Limit,
		p.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []PasteEvent
	for rows.Next() {
		var e PasteEvent
		var id, orgID, endpointID pgtype.UUID
		if err := rows.Scan(
			&id, &orgID, &endpointID, &e.DestinationDomain,
			&e.ContentLength, &e.ContentHash, &e.OSUsername,
			&e.OccurredAt, &e.ReceivedAt,
		); err != nil {
			return nil, err
		}
		e.ID = uuidFromPgtype(id)
		e.OrgID = uuidFromPgtype(orgID)
		e.SourceEndpointID = uuidFromPgtype(endpointID)
		out = append(out, e)
	}
	return out, rows.Err()
}

const countPasteEventsSQL = `
SELECT COUNT(*) FROM paste_events` + listPasteEventsWhereSQL

// CountPasteEvents returns the total row count matching the same filters
// as ListPasteEvents, for pagination metadata.
func (q *Queries) CountPasteEvents(ctx context.Context, p ListPasteEventsParams) (int64, error) {
	toTsArg := func(t *time.Time) pgtype.Timestamptz {
		if t == nil {
			return pgtype.Timestamptz{}
		}
		return pgtype.Timestamptz{Time: *t, Valid: true}
	}

	row := q.db.QueryRow(ctx, countPasteEventsSQL,
		toPgtypeUUID(p.OrgID),
		toPgtypeText(p.Domain),
		toTsArg(p.From),
		toTsArg(p.To),
	)
	var count int64
	return count, row.Scan(&count)
}
