// Code generated by sqlc from internal/store/query/policies.sql. DO NOT EDIT directly.
package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// listPoliciesQuery is the SQL for listing policies with conditions via LEFT JOIN.
// One row per policy; conditions columns are NULL if no conditions row exists.
const listPoliciesQuery = `-- name: ListPolicies :many
SELECT
    p.id, p.org_id, p.name, p.description, p.priority, p.action, p.alert, p.status,
    p.created_by, p.created_at, p.updated_at,
    pc.id AS cond_id,
    pc.agent_name_pattern, pc.tool_names, pc.action_types, pc.environments,
    pc.record_count_gt, pc.semantic_rule, COALESCE(pc.scope_drift, FALSE) AS scope_drift
FROM policies p
LEFT JOIN policy_conditions pc ON pc.policy_id = p.id
WHERE p.org_id = $1
  AND ($2::text IS NULL OR p.status = $2)
ORDER BY p.priority ASC
`

func (q *Queries) ListPolicies(ctx context.Context, orgID uuid.UUID, status *string) ([]PolicyRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesQuery, toPgtypeUUID(orgID), toPgtypeText(status))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []PolicyRow
	for rows.Next() {
		var r PolicyRow
		var condID pgtype.UUID
		if err := rows.Scan(
			&r.Policy.ID, &r.Policy.OrgID, &r.Policy.Name, &r.Policy.Description,
			&r.Policy.Priority, &r.Policy.Action, &r.Policy.Alert, &r.Policy.Status,
			&r.Policy.CreatedBy, &r.Policy.CreatedAt, &r.Policy.UpdatedAt,
			&condID,
			&r.Condition.AgentNamePattern, &r.Condition.ToolNames, &r.Condition.ActionTypes,
			&r.Condition.Environments, &r.Condition.RecordCountGT, &r.Condition.SemanticRule,
			&r.Condition.ScopeDrift,
		); err != nil {
			return nil, err
		}
		r.Condition.ID = uuidFromPgtype(condID)
		r.Condition.PolicyID = r.Policy.ID
		out = append(out, r)
	}
	return out, rows.Err()
}

const getPolicyQuery = `-- name: GetPolicy :one
SELECT
    p.id, p.org_id, p.name, p.description, p.priority, p.action, p.alert, p.status,
    p.created_by, p.created_at, p.updated_at,
    pc.id AS cond_id,
    pc.agent_name_pattern, pc.tool_names, pc.action_types, pc.environments,
    pc.record_count_gt, pc.semantic_rule, COALESCE(pc.scope_drift, FALSE) AS scope_drift
FROM policies p
LEFT JOIN policy_conditions pc ON pc.policy_id = p.id
WHERE p.id = $1 AND p.org_id = $2
LIMIT 1
`

func (q *Queries) GetPolicy(ctx context.Context, id, orgID uuid.UUID) (*PolicyRow, error) {
	row := q.db.QueryRow(ctx, getPolicyQuery, toPgtypeUUID(id), toPgtypeUUID(orgID))
	var r PolicyRow
	var condID pgtype.UUID
	err := row.Scan(
		&r.Policy.ID, &r.Policy.OrgID, &r.Policy.Name, &r.Policy.Description,
		&r.Policy.Priority, &r.Policy.Action, &r.Policy.Alert, &r.Policy.Status,
		&r.Policy.CreatedBy, &r.Policy.CreatedAt, &r.Policy.UpdatedAt,
		&condID,
		&r.Condition.AgentNamePattern, &r.Condition.ToolNames, &r.Condition.ActionTypes,
		&r.Condition.Environments, &r.Condition.RecordCountGT, &r.Condition.SemanticRule,
		&r.Condition.ScopeDrift,
	)
	if err != nil {
		return nil, err
	}
	r.Condition.ID = uuidFromPgtype(condID)
	r.Condition.PolicyID = r.Policy.ID
	return &r, nil
}

type CreatePolicyParams struct {
	OrgID       uuid.UUID
	Name        string
	Description pgtype.Text
	Priority    int32
	Action      string
	Alert       bool
	Status      string
	CreatedBy   pgtype.UUID
}

const createPolicyQuery = `-- name: CreatePolicy :one
INSERT INTO policies (org_id, name, description, priority, action, alert, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, description, priority, action, alert, status,
          created_by, created_at, updated_at
`

func (q *Queries) CreatePolicy(ctx context.Context, p CreatePolicyParams) (*Policy, error) {
	row := q.db.QueryRow(ctx, createPolicyQuery,
		toPgtypeUUID(p.OrgID), p.Name, p.Description, p.Priority,
		p.Action, p.Alert, p.Status, p.CreatedBy,
	)
	var pol Policy
	err := row.Scan(
		&pol.ID, &pol.OrgID, &pol.Name, &pol.Description, &pol.Priority,
		&pol.Action, &pol.Alert, &pol.Status, &pol.CreatedBy,
		&pol.CreatedAt, &pol.UpdatedAt,
	)
	return &pol, err
}

type CreatePolicyConditionParams struct {
	PolicyID         uuid.UUID
	AgentNamePattern pgtype.Text
	ToolNames        []string
	ActionTypes      []string
	Environments     []string
	RecordCountGT    pgtype.Int4
	SemanticRule     pgtype.Text
	ScopeDrift       bool
}

const createPolicyConditionQuery = `-- name: CreatePolicyCondition :one
INSERT INTO policy_conditions
    (policy_id, agent_name_pattern, tool_names, action_types, environments,
     record_count_gt, semantic_rule, scope_drift)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, policy_id, agent_name_pattern, tool_names, action_types, environments,
          record_count_gt, semantic_rule, scope_drift
`

func (q *Queries) CreatePolicyCondition(ctx context.Context, p CreatePolicyConditionParams) (*PolicyCondition, error) {
	row := q.db.QueryRow(ctx, createPolicyConditionQuery,
		toPgtypeUUID(p.PolicyID), p.AgentNamePattern, p.ToolNames, p.ActionTypes,
		p.Environments, p.RecordCountGT, p.SemanticRule, p.ScopeDrift,
	)
	var c PolicyCondition
	err := row.Scan(
		&c.ID, &c.PolicyID, &c.AgentNamePattern, &c.ToolNames, &c.ActionTypes,
		&c.Environments, &c.RecordCountGT, &c.SemanticRule, &c.ScopeDrift,
	)
	return &c, err
}

type UpdatePolicyParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Priority    pgtype.Int4
	Action      pgtype.Text
	Alert       *bool
	Status      pgtype.Text
}

const updatePolicyQuery = `-- name: UpdatePolicy :one
UPDATE policies SET
    name        = COALESCE($3, name),
    description = COALESCE($4, description),
    priority    = COALESCE($5, priority),
    action      = COALESCE($6, action),
    alert       = COALESCE($7, alert),
    status      = COALESCE($8, status)
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, priority, action, alert, status,
          created_by, created_at, updated_at
`

func (q *Queries) UpdatePolicy(ctx context.Context, p UpdatePolicyParams) (*Policy, error) {
	var alertArg interface{}
	if p.Alert != nil {
		alertArg = *p.Alert
	}
	row := q.db.QueryRow(ctx, updatePolicyQuery,
		toPgtypeUUID(p.ID), toPgtypeUUID(p.OrgID),
		p.Name, p.Description, p.Priority, p.Action, alertArg, p.Status,
	)
	var pol Policy
	err := row.Scan(
		&pol.ID, &pol.OrgID, &pol.Name, &pol.Description, &pol.Priority,
		&pol.Action, &pol.Alert, &pol.Status, &pol.CreatedBy,
		&pol.CreatedAt, &pol.UpdatedAt,
	)
	return &pol, err
}

const upsertPolicyConditionQuery = `-- name: UpsertPolicyCondition :exec
INSERT INTO policy_conditions
    (policy_id, agent_name_pattern, tool_names, action_types, environments,
     record_count_gt, semantic_rule, scope_drift)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (policy_id) DO UPDATE SET
    agent_name_pattern = EXCLUDED.agent_name_pattern,
    tool_names         = EXCLUDED.tool_names,
    action_types       = EXCLUDED.action_types,
    environments       = EXCLUDED.environments,
    record_count_gt    = EXCLUDED.record_count_gt,
    semantic_rule      = EXCLUDED.semantic_rule,
    scope_drift        = EXCLUDED.scope_drift
`

func (q *Queries) UpsertPolicyCondition(ctx context.Context, p CreatePolicyConditionParams) error {
	_, err := q.db.Exec(ctx, upsertPolicyConditionQuery,
		toPgtypeUUID(p.PolicyID), p.AgentNamePattern, p.ToolNames, p.ActionTypes,
		p.Environments, p.RecordCountGT, p.SemanticRule, p.ScopeDrift,
	)
	return err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = $1 AND org_id = $2
`

func (q *Queries) DeletePolicy(ctx context.Context, id, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicy, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return err
}

// reorderPoliciesBatchedQuery (B-090) replaces N single-row UPDATEs with one
// batched multi-row UPDATE via unnest() over two parallel arrays -- a fixed
// 3-parameter shape regardless of len(ids), so no dynamic SQL string-building
// is needed for a variable-length id list. Still scoped by org_id in the
// WHERE clause, same as the original per-row query -- a cross-org id in the
// input simply matches zero rows here. Security review (B-090/107 batch)
// caught a stale claim in an earlier version of this comment: on the
// production path (api.Server.ReorderPolicies with s.queries != nil) there
// is no handler-side per-id org membership check -- that loop only exists
// on the mock-backed test path. This WHERE clause is the ONLY thing
// enforcing org isolation here, not a backstop for a handler check that
// doesn't run in production.
// Query const kept as reorderPoliciesBatchedQuery (documents the batching
// approach for a reader of this file), but the sqlc :name annotation below
// is ReorderPolicies -- matching the actual Go function name -- because code
// review caught that these two files are meant to mirror what `sqlc
// generate` would emit (db.go's own doc comment says so): a mismatched
// annotation would regenerate a function named ReorderPoliciesBatched and
// silently break both of ReorderPolicies's real call sites (policies.go and
// the storeIface mock).
const reorderPoliciesBatchedQuery = `-- name: ReorderPolicies :exec
UPDATE policies AS p
SET priority = v.priority
FROM (SELECT unnest($1::uuid[]) AS id, unnest($2::int[]) AS priority) AS v
WHERE p.id = v.id AND p.org_id = $3
`

// ReorderPolicies renumbers priority sequentially (1-based) from each id's
// position in ids, in ONE batched UPDATE statement (B-090) rather than N
// sequential single-row UPDATEs wrapped in an explicit transaction (B-086's
// original fix).
//
// No explicit transaction here, unlike B-086's version -- investigated,
// not assumed: B-086's bug was specifically that N SEPARATE Exec() calls
// each auto-commit as their own independent statement, so an early id could
// transiently collide with a not-yet-updated row's still-current priority
// BETWEEN two separate commands, tripping the UNIQUE (org_id, priority)
// constraint before the deferred check ever got a chance to see the final,
// valid state. A single UPDATE...FROM statement computes every row's new
// value from one consistent read of the OLD data before applying any
// writes, and Postgres validates that single command's net effect as one
// atomic operation regardless of whether an outer transaction wraps it --
// there is no second command for an intermediate state to be checked
// against. Verified directly against the real running Postgres before
// removing the wrapper (not assumed from a query-plan reading): both a
// real adjacent-pair swap and a real 3-way rotation, each run as a bare
// single statement with NO surrounding BEGIN, land correctly with zero
// spurious unique-violation -- reproducing exactly the shape of case
// B-086 fixed, minus the transaction B-086 needed specifically because its
// fix was still N separate commands.
//
// This also narrows B-090's deadlock-window finding, though code review
// caught that an earlier version of this comment overstated it as fully
// "closed by construction" -- it isn't: two concurrent single-statement
// calls can still acquire this statement's row locks in opposite order and
// deadlock (Postgres error 40P01), which is exactly why the real
// concurrency test in policies_reorder_pg_test.go explicitly tolerates a
// real 40P01 as a safe, retryable outcome rather than asserting it never
// happens. What IS true, and is the actual improvement: every row lock this
// now takes is held for the duration of ONE statement's execution (a single
// round trip), never spread across N sequential client round trips the way
// the old loop's locks were -- so the deadlock WINDOW shrinks from
// "however long N round trips take" to "one statement's execution time,"
// not to zero.
func (q *Queries) ReorderPolicies(ctx context.Context, orgID uuid.UUID, ids []uuid.UUID) error {
	priorities := make([]int32, len(ids))
	for i := range ids {
		priorities[i] = int32(i + 1)
	}
	_, err := q.db.Exec(ctx, reorderPoliciesBatchedQuery, ids, priorities, toPgtypeUUID(orgID))
	return err
}
