// Code generated by sqlc from internal/store/query/policies.sql. DO NOT EDIT directly.
package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// listPoliciesQuery is the SQL for listing policies with conditions via LEFT JOIN.
// One row per policy; conditions columns are NULL if no conditions row exists.
const listPoliciesQuery = `-- name: ListPolicies :many
SELECT
    p.id, p.org_id, p.name, p.description, p.priority, p.action, p.alert, p.status,
    p.created_by, p.created_at, p.updated_at,
    pc.id AS cond_id,
    pc.agent_name_pattern, pc.tool_names, pc.action_types, pc.environments,
    pc.record_count_gt, pc.semantic_rule, COALESCE(pc.scope_drift, FALSE) AS scope_drift
FROM policies p
LEFT JOIN policy_conditions pc ON pc.policy_id = p.id
WHERE p.org_id = $1
  AND ($2::text IS NULL OR p.status = $2)
ORDER BY p.priority ASC
`

func (q *Queries) ListPolicies(ctx context.Context, orgID uuid.UUID, status *string) ([]PolicyRow, error) {
	rows, err := q.db.Query(ctx, listPoliciesQuery, toPgtypeUUID(orgID), toPgtypeText(status))
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var out []PolicyRow
	for rows.Next() {
		var r PolicyRow
		var condID pgtype.UUID
		if err := rows.Scan(
			&r.Policy.ID, &r.Policy.OrgID, &r.Policy.Name, &r.Policy.Description,
			&r.Policy.Priority, &r.Policy.Action, &r.Policy.Alert, &r.Policy.Status,
			&r.Policy.CreatedBy, &r.Policy.CreatedAt, &r.Policy.UpdatedAt,
			&condID,
			&r.Condition.AgentNamePattern, &r.Condition.ToolNames, &r.Condition.ActionTypes,
			&r.Condition.Environments, &r.Condition.RecordCountGT, &r.Condition.SemanticRule,
			&r.Condition.ScopeDrift,
		); err != nil {
			return nil, err
		}
		r.Condition.ID = uuidFromPgtype(condID)
		r.Condition.PolicyID = r.Policy.ID
		out = append(out, r)
	}
	return out, rows.Err()
}

const getPolicyQuery = `-- name: GetPolicy :one
SELECT
    p.id, p.org_id, p.name, p.description, p.priority, p.action, p.alert, p.status,
    p.created_by, p.created_at, p.updated_at,
    pc.id AS cond_id,
    pc.agent_name_pattern, pc.tool_names, pc.action_types, pc.environments,
    pc.record_count_gt, pc.semantic_rule, COALESCE(pc.scope_drift, FALSE) AS scope_drift
FROM policies p
LEFT JOIN policy_conditions pc ON pc.policy_id = p.id
WHERE p.id = $1 AND p.org_id = $2
LIMIT 1
`

func (q *Queries) GetPolicy(ctx context.Context, id, orgID uuid.UUID) (*PolicyRow, error) {
	row := q.db.QueryRow(ctx, getPolicyQuery, toPgtypeUUID(id), toPgtypeUUID(orgID))
	var r PolicyRow
	var condID pgtype.UUID
	err := row.Scan(
		&r.Policy.ID, &r.Policy.OrgID, &r.Policy.Name, &r.Policy.Description,
		&r.Policy.Priority, &r.Policy.Action, &r.Policy.Alert, &r.Policy.Status,
		&r.Policy.CreatedBy, &r.Policy.CreatedAt, &r.Policy.UpdatedAt,
		&condID,
		&r.Condition.AgentNamePattern, &r.Condition.ToolNames, &r.Condition.ActionTypes,
		&r.Condition.Environments, &r.Condition.RecordCountGT, &r.Condition.SemanticRule,
		&r.Condition.ScopeDrift,
	)
	if err != nil {
		return nil, err
	}
	r.Condition.ID = uuidFromPgtype(condID)
	r.Condition.PolicyID = r.Policy.ID
	return &r, nil
}

type CreatePolicyParams struct {
	OrgID       uuid.UUID
	Name        string
	Description pgtype.Text
	Priority    int32
	Action      string
	Alert       bool
	Status      string
	CreatedBy   pgtype.UUID
}

const createPolicyQuery = `-- name: CreatePolicy :one
INSERT INTO policies (org_id, name, description, priority, action, alert, status, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, org_id, name, description, priority, action, alert, status,
          created_by, created_at, updated_at
`

func (q *Queries) CreatePolicy(ctx context.Context, p CreatePolicyParams) (*Policy, error) {
	row := q.db.QueryRow(ctx, createPolicyQuery,
		toPgtypeUUID(p.OrgID), p.Name, p.Description, p.Priority,
		p.Action, p.Alert, p.Status, p.CreatedBy,
	)
	var pol Policy
	err := row.Scan(
		&pol.ID, &pol.OrgID, &pol.Name, &pol.Description, &pol.Priority,
		&pol.Action, &pol.Alert, &pol.Status, &pol.CreatedBy,
		&pol.CreatedAt, &pol.UpdatedAt,
	)
	return &pol, err
}

type CreatePolicyConditionParams struct {
	PolicyID         uuid.UUID
	AgentNamePattern pgtype.Text
	ToolNames        []string
	ActionTypes      []string
	Environments     []string
	RecordCountGT    pgtype.Int4
	SemanticRule     pgtype.Text
	ScopeDrift       bool
}

const createPolicyConditionQuery = `-- name: CreatePolicyCondition :one
INSERT INTO policy_conditions
    (policy_id, agent_name_pattern, tool_names, action_types, environments,
     record_count_gt, semantic_rule, scope_drift)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, policy_id, agent_name_pattern, tool_names, action_types, environments,
          record_count_gt, semantic_rule, scope_drift
`

func (q *Queries) CreatePolicyCondition(ctx context.Context, p CreatePolicyConditionParams) (*PolicyCondition, error) {
	row := q.db.QueryRow(ctx, createPolicyConditionQuery,
		toPgtypeUUID(p.PolicyID), p.AgentNamePattern, p.ToolNames, p.ActionTypes,
		p.Environments, p.RecordCountGT, p.SemanticRule, p.ScopeDrift,
	)
	var c PolicyCondition
	err := row.Scan(
		&c.ID, &c.PolicyID, &c.AgentNamePattern, &c.ToolNames, &c.ActionTypes,
		&c.Environments, &c.RecordCountGT, &c.SemanticRule, &c.ScopeDrift,
	)
	return &c, err
}

type UpdatePolicyParams struct {
	ID          uuid.UUID
	OrgID       uuid.UUID
	Name        pgtype.Text
	Description pgtype.Text
	Priority    pgtype.Int4
	Action      pgtype.Text
	Alert       *bool
	Status      pgtype.Text
}

const updatePolicyQuery = `-- name: UpdatePolicy :one
UPDATE policies SET
    name        = COALESCE($3, name),
    description = COALESCE($4, description),
    priority    = COALESCE($5, priority),
    action      = COALESCE($6, action),
    alert       = COALESCE($7, alert),
    status      = COALESCE($8, status)
WHERE id = $1 AND org_id = $2
RETURNING id, org_id, name, description, priority, action, alert, status,
          created_by, created_at, updated_at
`

func (q *Queries) UpdatePolicy(ctx context.Context, p UpdatePolicyParams) (*Policy, error) {
	var alertArg interface{}
	if p.Alert != nil {
		alertArg = *p.Alert
	}
	row := q.db.QueryRow(ctx, updatePolicyQuery,
		toPgtypeUUID(p.ID), toPgtypeUUID(p.OrgID),
		p.Name, p.Description, p.Priority, p.Action, alertArg, p.Status,
	)
	var pol Policy
	err := row.Scan(
		&pol.ID, &pol.OrgID, &pol.Name, &pol.Description, &pol.Priority,
		&pol.Action, &pol.Alert, &pol.Status, &pol.CreatedBy,
		&pol.CreatedAt, &pol.UpdatedAt,
	)
	return &pol, err
}

const upsertPolicyConditionQuery = `-- name: UpsertPolicyCondition :exec
INSERT INTO policy_conditions
    (policy_id, agent_name_pattern, tool_names, action_types, environments,
     record_count_gt, semantic_rule, scope_drift)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (policy_id) DO UPDATE SET
    agent_name_pattern = EXCLUDED.agent_name_pattern,
    tool_names         = EXCLUDED.tool_names,
    action_types       = EXCLUDED.action_types,
    environments       = EXCLUDED.environments,
    record_count_gt    = EXCLUDED.record_count_gt,
    semantic_rule      = EXCLUDED.semantic_rule,
    scope_drift        = EXCLUDED.scope_drift
`

func (q *Queries) UpsertPolicyCondition(ctx context.Context, p CreatePolicyConditionParams) error {
	_, err := q.db.Exec(ctx, upsertPolicyConditionQuery,
		toPgtypeUUID(p.PolicyID), p.AgentNamePattern, p.ToolNames, p.ActionTypes,
		p.Environments, p.RecordCountGT, p.SemanticRule, p.ScopeDrift,
	)
	return err
}

const deletePolicy = `-- name: DeletePolicy :exec
DELETE FROM policies WHERE id = $1 AND org_id = $2
`

func (q *Queries) DeletePolicy(ctx context.Context, id, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePolicy, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return err
}

const reorderPoliciesQuery = `-- name: ReorderPolicies :exec
UPDATE policies SET priority = $2 WHERE id = $1 AND org_id = $3
`

func (q *Queries) ReorderPolicies(ctx context.Context, orgID uuid.UUID, ids []uuid.UUID) error {
	for i, id := range ids {
		if _, err := q.db.Exec(ctx, reorderPoliciesQuery, toPgtypeUUID(id), int32(i+1), toPgtypeUUID(orgID)); err != nil {
			return err
		}
	}
	return nil
}
