// Code generated by sqlc from internal/store/query/settings.sql. DO NOT EDIT directly.
// Re-generate: sqlc generate
// NOTE: requires migration 002_settings.sql to be applied first.
package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getOrgSettingsQuery = `-- name: GetOrgSettings :one
SELECT id, name, slug, plan,
       COALESCE(timezone, 'UTC') AS timezone,
       COALESCE(default_risk_tier, 'low') AS default_risk_tier,
       updated_at
FROM orgs WHERE id = $1`

func (q *Queries) GetOrgSettings(ctx context.Context, orgID uuid.UUID) (*OrgSettings, error) {
	row := q.db.QueryRow(ctx, getOrgSettingsQuery, toPgtypeUUID(orgID))
	var o OrgSettings
	err := row.Scan(&o.ID, &o.Name, &o.Slug, &o.Plan, &o.Timezone, &o.DefaultRiskTier, &o.UpdatedAt)
	if err != nil {
		return nil, err
	}
	return &o, nil
}

type UpdateOrgSettingsParams struct {
	OrgID           uuid.UUID
	Name            pgtype.Text
	Timezone        pgtype.Text
	DefaultRiskTier pgtype.Text
}

const updateOrgSettingsQuery = `-- name: UpdateOrgSettings :one
UPDATE orgs SET
    name              = COALESCE($2, name),
    timezone          = COALESCE($3, timezone),
    default_risk_tier = COALESCE($4, default_risk_tier)
WHERE id = $1
RETURNING id, name, slug, plan,
          COALESCE(timezone, 'UTC') AS timezone,
          COALESCE(default_risk_tier, 'low') AS default_risk_tier,
          updated_at`

func (q *Queries) UpdateOrgSettings(ctx context.Context, p UpdateOrgSettingsParams) (*OrgSettings, error) {
	row := q.db.QueryRow(ctx, updateOrgSettingsQuery,
		toPgtypeUUID(p.OrgID), p.Name, p.Timezone, p.DefaultRiskTier,
	)
	var o OrgSettings
	err := row.Scan(&o.ID, &o.Name, &o.Slug, &o.Plan, &o.Timezone, &o.DefaultRiskTier, &o.UpdatedAt)
	if err != nil {
		return nil, err
	}
	return &o, nil
}

const getNotificationConfigQuery = `-- name: GetNotificationConfig :one
SELECT org_id, slack_enabled, slack_webhook_url, email_enabled,
       email_smtp_host, email_smtp_port, email_from, updated_at
FROM notification_config WHERE org_id = $1`

func (q *Queries) GetNotificationConfig(ctx context.Context, orgID uuid.UUID) (*NotificationConfig, error) {
	row := q.db.QueryRow(ctx, getNotificationConfigQuery, toPgtypeUUID(orgID))
	var n NotificationConfig
	err := row.Scan(
		&n.OrgID, &n.SlackEnabled, &n.SlackWebhookURL, &n.EmailEnabled,
		&n.EmailSMTPHost, &n.EmailSMTPPort, &n.EmailFrom, &n.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &n, nil
}

type UpsertNotificationConfigParams struct {
	OrgID           uuid.UUID
	SlackEnabled    bool
	SlackWebhookURL pgtype.Text
	EmailEnabled    bool
	EmailSMTPHost   pgtype.Text
	EmailSMTPPort   int32
	EmailFrom       pgtype.Text
}

const upsertNotificationConfigQuery = `-- name: UpsertNotificationConfig :one
INSERT INTO notification_config (
    org_id, slack_enabled, slack_webhook_url,
    email_enabled, email_smtp_host, email_smtp_port, email_from
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (org_id) DO UPDATE SET
    slack_enabled     = EXCLUDED.slack_enabled,
    slack_webhook_url = EXCLUDED.slack_webhook_url,
    email_enabled     = EXCLUDED.email_enabled,
    email_smtp_host   = EXCLUDED.email_smtp_host,
    email_smtp_port   = EXCLUDED.email_smtp_port,
    email_from        = EXCLUDED.email_from,
    updated_at        = NOW()
RETURNING org_id, slack_enabled, slack_webhook_url, email_enabled,
          email_smtp_host, email_smtp_port, email_from, updated_at`

func (q *Queries) UpsertNotificationConfig(ctx context.Context, p UpsertNotificationConfigParams) (*NotificationConfig, error) {
	row := q.db.QueryRow(ctx, upsertNotificationConfigQuery,
		toPgtypeUUID(p.OrgID), p.SlackEnabled, p.SlackWebhookURL,
		p.EmailEnabled, p.EmailSMTPHost, p.EmailSMTPPort, p.EmailFrom,
	)
	var n NotificationConfig
	err := row.Scan(
		&n.OrgID, &n.SlackEnabled, &n.SlackWebhookURL, &n.EmailEnabled,
		&n.EmailSMTPHost, &n.EmailSMTPPort, &n.EmailFrom, &n.UpdatedAt,
	)
	if err != nil {
		return nil, err
	}
	return &n, nil
}
