// Code generated by hand from internal/store/query/token_usage.sql. DO NOT run sqlc.
package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// ModelPricing holds per-1k-token costs for a model.
type ModelPricing struct {
	CostPer1kIn  float64
	CostPer1kOut float64
}

const getModelPricingSQL = `
SELECT cost_per_1k_in, cost_per_1k_out
FROM model_pricing
WHERE model = $1`

// GetModelPricing fetches the cost rates for a model.
// Returns (zero ModelPricing, pgx.ErrNoRows) when the model is not in the table.
func (q *Queries) GetModelPricing(ctx context.Context, model string) (ModelPricing, error) {
	row := q.db.QueryRow(ctx, getModelPricingSQL, model)
	var mp ModelPricing
	err := row.Scan(&mp.CostPer1kIn, &mp.CostPer1kOut)
	return mp, err
}

// InsertTokenUsageParams holds parameters for InsertTokenUsage.
type InsertTokenUsageParams struct {
	OrgID     uuid.UUID
	AgentID   uuid.UUID // zero value treated as NULL
	AgentName string
	Model     string
	ToolName  string // empty treated as NULL (B-108) -- unresolved-tool calls have none
	TokensIn  int32
	TokensOut int32
	CostUSD   float64
	// CacheCreation5mTokens/CacheCreation1hTokens/CacheReadTokens (B-111)
	// are raw Anthropic prompt-caching counters, stored as plain
	// NOT NULL DEFAULT 0 columns -- no NULL-encoding needed, unlike
	// ToolName/CostUSD above. Cost for these is never computed or stored
	// here -- finops.go prices them at query time from current
	// model_pricing rates.
	CacheCreation5mTokens int32
	CacheCreation1hTokens int32
	CacheReadTokens       int32
	RecordedAt            time.Time
}

const insertTokenUsageSQL = `
INSERT INTO token_usage
    (org_id, agent_id, agent_name, model, tool_name, tokens_in, tokens_out, cost_usd,
     cache_creation_5m_tokens, cache_creation_1h_tokens, cache_read_tokens, recorded_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)`

// InsertTokenUsage writes one token-usage row.
// When AgentID is the zero UUID it is stored as NULL.
func (q *Queries) InsertTokenUsage(ctx context.Context, p InsertTokenUsageParams) error {
	// Encode org_id — always required.
	orgID := toPgtypeUUID(p.OrgID)

	// Encode agent_id — NULL when zero.
	var agentID pgtype.UUID
	if p.AgentID != (uuid.UUID{}) {
		agentID = pgtype.UUID{Bytes: p.AgentID, Valid: true}
	}

	// Encode tool_name — NULL when empty (B-108).
	var toolName pgtype.Text
	if p.ToolName != "" {
		toolName = pgtype.Text{String: p.ToolName, Valid: true}
	}

	// Encode cost — NULL when zero (allows the finops fallback computation to kick in).
	var costUSD pgtype.Float8
	if p.CostUSD > 0 {
		costUSD = pgtype.Float8{Float64: p.CostUSD, Valid: true}
	}

	recordedAt := pgtype.Timestamptz{Time: p.RecordedAt.UTC(), Valid: true}

	_, err := q.db.Exec(ctx, insertTokenUsageSQL,
		orgID,
		agentID,
		p.AgentName,
		p.Model,
		toolName,
		p.TokensIn,
		p.TokensOut,
		costUSD,
		p.CacheCreation5mTokens,
		p.CacheCreation1hTokens,
		p.CacheReadTokens,
		recordedAt,
	)
	return err
}
