// Code generated by sqlc from internal/store/query/users.sql. DO NOT EDIT directly.
// NOTE: requires migration 002_settings.sql (adds deleted_at, invited_at, invited_by columns).
package store

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// UserRow is the subset of user columns needed for management endpoints.
type UserRow struct {
	ID        uuid.UUID
	OrgID     uuid.UUID
	Email     string
	Name      pgtype.Text
	Role      string
	CreatedAt time.Time
	LastLogin pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

const listUsersQuery = `-- name: ListUsers :many
SELECT id, org_id, email, name, role, created_at, last_login, deleted_at
FROM users WHERE org_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2 OFFSET $3`

func (q *Queries) ListUsers(ctx context.Context, orgID uuid.UUID, limit, offset int32) ([]UserRow, error) {
	rows, err := q.db.Query(ctx, listUsersQuery, toPgtypeUUID(orgID), limit, offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var out []UserRow
	for rows.Next() {
		var u UserRow
		if err := rows.Scan(&u.ID, &u.OrgID, &u.Email, &u.Name, &u.Role,
			&u.CreatedAt, &u.LastLogin, &u.DeletedAt); err != nil {
			return nil, err
		}
		out = append(out, u)
	}
	return out, rows.Err()
}

const countUsersQuery = `-- name: CountUsers :one
SELECT COUNT(*) FROM users WHERE org_id = $1 AND deleted_at IS NULL`

func (q *Queries) CountUsers(ctx context.Context, orgID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUsersQuery, toPgtypeUUID(orgID))
	var count int64
	return count, row.Scan(&count)
}

type CreateInvitedUserParams struct {
	OrgID     uuid.UUID
	Email     string
	Role      string
	InvitedBy pgtype.UUID
}

const createInvitedUserQuery = `-- name: CreateInvitedUser :one
INSERT INTO users (org_id, email, role, invited_at, invited_by)
VALUES ($1, $2, $3, NOW(), $4)
RETURNING id, org_id, email, name, role, created_at, last_login, deleted_at`

func (q *Queries) CreateInvitedUser(ctx context.Context, p CreateInvitedUserParams) (*UserRow, error) {
	row := q.db.QueryRow(ctx, createInvitedUserQuery,
		toPgtypeUUID(p.OrgID), p.Email, p.Role, p.InvitedBy,
	)
	var u UserRow
	err := row.Scan(&u.ID, &u.OrgID, &u.Email, &u.Name, &u.Role,
		&u.CreatedAt, &u.LastLogin, &u.DeletedAt)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

const updateUserRoleQuery = `-- name: UpdateUserRole :one
UPDATE users SET role = $3
WHERE id = $1 AND org_id = $2 AND deleted_at IS NULL
RETURNING id, org_id, email, name, role, created_at, last_login, deleted_at`

func (q *Queries) UpdateUserRole(ctx context.Context, id, orgID uuid.UUID, role string) (*UserRow, error) {
	row := q.db.QueryRow(ctx, updateUserRoleQuery, toPgtypeUUID(id), toPgtypeUUID(orgID), role)
	var u UserRow
	err := row.Scan(&u.ID, &u.OrgID, &u.Email, &u.Name, &u.Role,
		&u.CreatedAt, &u.LastLogin, &u.DeletedAt)
	if err != nil {
		return nil, err
	}
	return &u, nil
}

const softDeleteUserQuery = `-- name: SoftDeleteUser :exec
UPDATE users SET deleted_at = NOW() WHERE id = $1 AND org_id = $2`

func (q *Queries) SoftDeleteUser(ctx context.Context, id, orgID uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteUserQuery, toPgtypeUUID(id), toPgtypeUUID(orgID))
	return err
}
