#!/usr/bin/env bash
# =============================================================================
# EAMI appliance — stack bring-up (runs at every boot, via eami-stack.service,
# After=docker.service)
# =============================================================================
# Secrets and the first-boot marker live on the DATA disk (/data/eami), not
# the OS disk (/opt/eami) -- deliberately. /opt/eami is the static
# application bundle (docker-compose.prod.yml, migrations, backup scripts),
# replaced wholesale by every OS image update. If secrets lived there too,
# an OS update would silently regenerate POSTGRES_PASSWORD/
# TOOL_CREDENTIALS_ENCRYPTION_KEY/etc. on next boot -- the docker volumes'
# raw files would survive (AC6's literal wording) but be unusable, since a
# fresh Postgres password wouldn't match the already-initialized database's
# own auth, and a fresh encryption key can't decrypt data encrypted under
# the old one. Keeping secrets on /data makes "update survives" mean
# "actually still works", not just "files still exist".
#
# Non-interactive by design: ported from scripts/setup.sh's secret
# generators (gen_password/generate_secret/gen_uuid), but deliberately
# drops setup.sh's collect_inputs/seed_database steps entirely -- this
# appliance must boot into a genuinely empty `orgs` table (AC3), never
# auto-seed an org/admin. That's the future setup wizard's job, not this
# script's.
# =============================================================================
set -euo pipefail

log() { echo "[eami-stack] $*"; }

OPT_DIR=/opt/eami
DATA_DIR=/data/eami
ENV_FILE="${DATA_DIR}/.env"
STATE_FILE="${DATA_DIR}/state"

mkdir -p "$DATA_DIR"

# 64-hex-char (256-bit) secret -- hex-only deliberately (B-051's own
# .env.example fix: a base64-alphabet password can contain postgres://
# URL-reserved characters and misparse in the migrate service's DSN).
gen_hex_secret() { openssl rand -hex 32; }

if [[ -f "$ENV_FILE" ]]; then
    log "${ENV_FILE} already exists -- reusing existing secrets (not regenerating)"
else
    log "No existing ${ENV_FILE} -- generating secrets for first boot"

    POSTGRES_PASSWORD="$(gen_hex_secret)"
    SERVICE_KEY="$(gen_hex_secret)"                # shared: API_SERVICE_KEY == GATEWAY_API_SERVICE_KEY
    COLLECTOR_API_KEY="$(gen_hex_secret)"           # shared: eami-collector + eami-api
    GATEWAY_EPISODE_READ_SERVICE_KEY="$(gen_hex_secret)"   # shared: eami-gateway + eami-api proxy
    GATEWAY_TOKEN_REVOKE_SERVICE_KEY="$(gen_hex_secret)"   # gateway-local (B-042)
    TOOL_CREDENTIALS_ENCRYPTION_KEY="$(gen_hex_secret)"    # shared: eami-gateway + eami-api (B-022/B-044)

    # Best-effort primary IP for GATEWAY_UI_BASE_URL (used only to build
    # links in Slack approval notifications -- not required for the stack
    # to start or for AC1-AC3). Falls back to localhost; the admin can
    # correct it in /data/eami/.env once they know the appliance's real
    # reachable address, matching setup.sh's own SERVER_IP-detection
    # fallback behavior.
    SERVER_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
    SERVER_IP="${SERVER_IP:-localhost}"

    umask 077
    cat > "$ENV_FILE" <<EOF
# EAMI appliance -- generated by eami-stack.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Lives on the data disk deliberately -- see this script's own header comment.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
API_SERVICE_KEY=${SERVICE_KEY}
GATEWAY_API_SERVICE_KEY=${SERVICE_KEY}
GATEWAY_EPISODE_READ_SERVICE_KEY=${GATEWAY_EPISODE_READ_SERVICE_KEY}
GATEWAY_TOKEN_REVOKE_SERVICE_KEY=${GATEWAY_TOKEN_REVOKE_SERVICE_KEY}
TOOL_CREDENTIALS_ENCRYPTION_KEY=${TOOL_CREDENTIALS_ENCRYPTION_KEY}
GATEWAY_UI_BASE_URL=http://${SERVER_IP}
GATEWAY_APPROVAL_SLACK_WEBHOOK=
GATEWAY_PPROF_ADDR=
EOF
    chmod 600 "$ENV_FILE"
    log "Wrote ${ENV_FILE} (chmod 600)"
fi

log "Starting stack: docker compose -f ${OPT_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE} up -d"
docker compose -f "${OPT_DIR}/docker-compose.prod.yml" --env-file "$ENV_FILE" up -d

if [[ -f "$STATE_FILE" ]]; then
    log "${STATE_FILE} already exists ($(cat "$STATE_FILE")) -- leaving as-is"
else
    echo "unconfigured" > "$STATE_FILE"
    log "Wrote ${STATE_FILE} = unconfigured (first boot -- no org/admin exists yet)"
fi

log "eami-stack complete"
