#!/usr/bin/env bash
# =============================================================================
# EAMI appliance — stack bring-up (runs at every boot, via eami-stack.service,
# After=docker.service)
# =============================================================================
# Secrets and the first-boot marker live on the DATA disk (/data/eami), not
# the OS disk (/opt/eami) -- deliberately. /opt/eami is the static
# application bundle (docker-compose.prod.yml, migrations, backup scripts),
# replaced wholesale by every OS image update. If secrets lived there too,
# an OS update would silently regenerate POSTGRES_PASSWORD/
# TOOL_CREDENTIALS_ENCRYPTION_KEY/etc. on next boot -- the docker volumes'
# raw files would survive (AC6's literal wording) but be unusable, since a
# fresh Postgres password wouldn't match the already-initialized database's
# own auth, and a fresh encryption key can't decrypt data encrypted under
# the old one. Keeping secrets on /data makes "update survives" mean
# "actually still works", not just "files still exist".
#
# Non-interactive by design: ported from scripts/setup.sh's secret
# generators (gen_password/generate_secret/gen_uuid), but deliberately
# drops setup.sh's collect_inputs/seed_database steps entirely -- this
# appliance must boot into a genuinely empty `orgs` table (AC3), never
# auto-seed an org/admin. That's the future setup wizard's job, not this
# script's.
# =============================================================================
set -euo pipefail

log() { echo "[eami-stack] $*"; }

OPT_DIR=/opt/eami
DATA_DIR=/data/eami
ENV_FILE="${DATA_DIR}/.env"
STATE_FILE="${DATA_DIR}/state"

mkdir -p "$DATA_DIR"

# 64-hex-char (256-bit) secret -- hex-only deliberately (B-051's own
# .env.example fix: a base64-alphabet password can contain postgres://
# URL-reserved characters and misparse in the migrate service's DSN).
gen_hex_secret() { openssl rand -hex 32; }

if [[ -f "$ENV_FILE" ]]; then
    log "${ENV_FILE} already exists -- reusing existing secrets (not regenerating)"
    # B-071, a real gap a security review caught: an appliance provisioned
    # BEFORE this brief shipped has an existing .env with no EAMI_CERT_DIR
    # key at all -- exactly the "OS image update, .env survives on the data
    # disk" scenario this script's own header comment exists to protect.
    # Without this backfill, docker-compose.prod.yml's
    # ${EAMI_CERT_DIR:-./certs}/custom would silently fall back to a path
    # relative to /opt/eami (the OS disk, wiped on every image update)
    # instead of the data disk -- an admin who follows README.md's exact
    # instructions (drop a cert at /data/eami/certs/custom, restart
    # eami-proxy) would see no error, but eami-proxy would keep using the
    # self-signed default because it's bind-mounted from the wrong
    # directory. Append-only: never touches any existing secret.
    if ! grep -q '^EAMI_CERT_DIR=' "$ENV_FILE"; then
        echo "EAMI_CERT_DIR=${DATA_DIR}/certs" >> "$ENV_FILE"
        log "Backfilled EAMI_CERT_DIR into existing ${ENV_FILE}"
    fi
    # Same backfill, same reasoning, for eami-proxy's redirect-target host
    # (B-071) -- an appliance provisioned before this brief has no
    # EAMI_PUBLIC_HOST either. Best-effort re-detection here (not a stored
    # value from first boot) since the appliance's IP could legitimately
    # differ from whatever it was at original provisioning time.
    if ! grep -q '^EAMI_PUBLIC_HOST=' "$ENV_FILE"; then
        BACKFILL_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
        echo "EAMI_PUBLIC_HOST=${BACKFILL_IP:-localhost}" >> "$ENV_FILE"
        log "Backfilled EAMI_PUBLIC_HOST into existing ${ENV_FILE}"
    fi
else
    log "No existing ${ENV_FILE} -- generating secrets for first boot"

    POSTGRES_PASSWORD="$(gen_hex_secret)"
    SERVICE_KEY="$(gen_hex_secret)"                # shared: API_SERVICE_KEY == GATEWAY_API_SERVICE_KEY
    COLLECTOR_API_KEY="$(gen_hex_secret)"           # shared: eami-collector + eami-api
    GATEWAY_EPISODE_READ_SERVICE_KEY="$(gen_hex_secret)"   # shared: eami-gateway + eami-api proxy
    GATEWAY_TOKEN_REVOKE_SERVICE_KEY="$(gen_hex_secret)"   # gateway-local (B-042)
    TOOL_CREDENTIALS_ENCRYPTION_KEY="$(gen_hex_secret)"    # shared: eami-gateway + eami-api (B-022/B-044)

    # Best-effort primary IP for GATEWAY_UI_BASE_URL (used only to build
    # links in Slack approval notifications -- not required for the stack
    # to start or for AC1-AC3). Falls back to localhost; the admin can
    # correct it in /data/eami/.env once they know the appliance's real
    # reachable address, matching setup.sh's own SERVER_IP-detection
    # fallback behavior.
    SERVER_IP="$(hostname -I 2>/dev/null | awk '{print $1}')"
    SERVER_IP="${SERVER_IP:-localhost}"

    umask 077
    cat > "$ENV_FILE" <<EOF
# EAMI appliance -- generated by eami-stack.sh on $(date -u '+%Y-%m-%dT%H:%M:%SZ')
# Lives on the data disk deliberately -- see this script's own header comment.
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
COLLECTOR_API_KEY=${COLLECTOR_API_KEY}
API_SERVICE_KEY=${SERVICE_KEY}
GATEWAY_API_SERVICE_KEY=${SERVICE_KEY}
GATEWAY_EPISODE_READ_SERVICE_KEY=${GATEWAY_EPISODE_READ_SERVICE_KEY}
GATEWAY_TOKEN_REVOKE_SERVICE_KEY=${GATEWAY_TOKEN_REVOKE_SERVICE_KEY}
TOOL_CREDENTIALS_ENCRYPTION_KEY=${TOOL_CREDENTIALS_ENCRYPTION_KEY}
# https, not http (B-071) -- the UI is only ever reachable via eami-proxy's
# TLS listener now; this value is used solely to build links in Slack
# approval notifications, not required for the stack to start.
GATEWAY_UI_BASE_URL=https://${SERVER_IP}
GATEWAY_APPROVAL_SLACK_WEBHOOK=
GATEWAY_PPROF_ADDR=
# B-071: directory eami-proxy checks for a customer-supplied certificate
# (fullchain.pem/privkey.pem in a "custom" subdirectory) -- see
# appliance/README.md's "TLS certificates" section. Lives on the data disk
# like every other secret/cert this script manages, so it survives an OS
# image update. Falls back to Caddy's own self-signed internal CA
# automatically if this directory has no cert in it.
EAMI_CERT_DIR=${DATA_DIR}/certs
# B-071: eami-proxy's :80 -> :443 redirect target, and (when using the
# self-signed default) the identifier its internal cert is issued for.
# Same best-effort IP detection as GATEWAY_UI_BASE_URL above, deliberately
# NOT derived from any client-supplied value.
EAMI_PUBLIC_HOST=${SERVER_IP}
EOF
    chmod 600 "$ENV_FILE"
    log "Wrote ${ENV_FILE} (chmod 600)"
fi

# Ensure the custom-cert directory exists on every boot, not just first boot
# -- an admin should be able to drop a certificate in and restart eami-proxy
# at any time, without needing to delete/regenerate the whole .env file
# first. mkdir -p is a no-op if it already exists (e.g. every boot after
# the first).
mkdir -p "${DATA_DIR}/certs/custom"

log "Starting stack: docker compose -f ${OPT_DIR}/docker-compose.prod.yml --env-file ${ENV_FILE} up -d"
docker compose -f "${OPT_DIR}/docker-compose.prod.yml" --env-file "$ENV_FILE" up -d

if [[ -f "$STATE_FILE" ]]; then
    log "${STATE_FILE} already exists ($(cat "$STATE_FILE")) -- leaving as-is"
else
    echo "unconfigured" > "$STATE_FILE"
    log "Wrote ${STATE_FILE} = unconfigured (first boot -- no org/admin exists yet)"
fi

# =============================================================================
# First-boot setup wizard token (setup-wizard brief, follows B-053)
# =============================================================================
# The setup wizard's eami-api endpoints are network-reachable but require
# this token to create anything (see eami-api/internal/api/bootstrap.go) --
# the token is only ever displayed here, on the VM console, the same trusted
# channel README.md already documents (SSH is permanently disabled, so
# journal+console -- see eami-stack.service's StandardOutput -- is this
# appliance's one emergency/first-access surface). Reusing that boundary
# rather than inventing a new one is deliberate, per this brief's own
# requirement.
#
# The real "is this appliance configured" gate is the orgs table itself
# (docker-compose.prod.yml is frozen, so eami-api has no way to be given a
# bind-mount of /data/eami/state -- see README.md's first-boot contract
# section for the full reasoning). This step re-derives that same signal by
# querying Postgres directly, exactly like scripts/setup.sh's own
# seed_database step already does via `docker compose exec postgres psql`.
COMPOSE_CMD=(docker compose -f "${OPT_DIR}/docker-compose.prod.yml" --env-file "$ENV_FILE")

ORG_COUNT="$("${COMPOSE_CMD[@]}" exec -T postgres \
    psql -U eami_app -d eami -tAc 'SELECT count(*) FROM orgs;' | tr -d '[:space:]')"

if [[ "$ORG_COUNT" =~ ^[0-9]+$ ]] && [[ "$ORG_COUNT" -gt 0 ]]; then
    log "Appliance already configured (${ORG_COUNT} org(s) exist) -- no setup token needed"
    # Best-effort reconciliation only -- the file is informational, the orgs
    # table above is the real gate the API itself checks on every request.
    if [[ -f "$STATE_FILE" ]] && [[ "$(cat "$STATE_FILE")" != "configured" ]]; then
        echo "configured" > "$STATE_FILE"
        log "Updated ${STATE_FILE} = configured"
    fi
else
    log "Appliance not yet configured -- generating a one-time setup wizard token"

    # Only one live (unconsumed) token at a time -- an old, still-valid token
    # from a prior boot would otherwise keep working even after a fresh one
    # is issued, and would linger unnoticed in console scrollback.
    "${COMPOSE_CMD[@]}" exec -T postgres \
        psql -U eami_app -d eami -v ON_ERROR_STOP=1 \
        -c "DELETE FROM setup_tokens WHERE consumed_at IS NULL;" >/dev/null

    SETUP_TOKEN="$(openssl rand -hex 32)"
    SETUP_TOKEN_HASH="$(printf '%s' "$SETUP_TOKEN" | openssl dgst -sha256 | awk '{print $2}')"

    "${COMPOSE_CMD[@]}" exec -T postgres \
        psql -U eami_app -d eami -v ON_ERROR_STOP=1 \
        -c "INSERT INTO setup_tokens (token_hash, expires_at) VALUES ('${SETUP_TOKEN_HASH}', now() + interval '30 minutes');" >/dev/null

    SERVER_IP_DISPLAY="$(hostname -I 2>/dev/null | awk '{print $1}')"
    SERVER_IP_DISPLAY="${SERVER_IP_DISPLAY:-<this-VMs-IP>}"

    echo ""
    echo "=============================================================="
    echo " EAMI first-boot setup"
    echo "=============================================================="
    echo " This appliance has no organization or admin account yet."
    echo " Open the setup wizard in a browser:"
    echo ""
    echo "   https://${SERVER_IP_DISPLAY}/setup"
    echo ""
    echo " (TLS-terminated by eami-proxy, B-071 -- your browser will warn"
    echo " about the self-signed certificate unless a real one has been"
    echo " installed; see appliance/README.md's \"TLS certificates\" section.)"
    echo ""
    echo " Setup token (single use, expires in 30 minutes):"
    echo ""
    echo "   ${SETUP_TOKEN}"
    echo ""
    echo " This token is shown ONLY here, on the console -- it is never sent"
    echo " over the network by this appliance. Reboot the VM to get a fresh"
    echo " token if this one is lost or expires."
    echo "=============================================================="
    echo ""
fi

log "eami-stack complete"
